import type { ClientAction } from '../../shared/types/client-actions.js';
import type { ApprovalBatch } from '../../shared/types/approvals.js';
import type { NormalizedDecision } from '../../shared/types/decision.js';

// ── Badge labels ───────────────────────────────────────────────────────────

const CLIENT_ACTION_BADGES: Record<string, string> = {
  aeo_change:        'AEO',
  internal_link:     'Internal Links',
  redirect_proposal: 'Redirects',
  content_decay:     'Content',
  keyword_strategy:  'Keywords',   // deprecated; archived rows only
};

/**
 * Infer a short human badge from an approval_batch name.
 * Batch names are generated by admin tools: "SEO Editor — N pages",
 * "Schema — N pages", "CMS Editor — collection".
 */
export function badgeForBatch(name: string): string {
  const lower = name.toLowerCase();
  if (lower.startsWith('schema')) return 'Schema';
  if (lower.startsWith('cms')) return 'CMS';
  if (lower.startsWith('seo editor') || lower.startsWith('seo')) return 'SEO Editor';
  if (lower.startsWith('audit')) return 'Audit';
  return 'SEO';   // fallback
}

// ── Item count helpers ────────────────────────────────────────────────────

/**
 * For client_actions, itemCount reflects the number of individual changes
 * inside the payload. Falls back to 1 (the action itself is the single item).
 */
function itemCountForAction(action: ClientAction): number {
  const p = action.payload as Record<string, unknown>;
  if (Array.isArray(p?.diffs)) return (p.diffs as unknown[]).length;
  if (Array.isArray(p?.suggestions)) return (p.suggestions as unknown[]).length;
  if (Array.isArray(p?.redirects)) return (p.redirects as unknown[]).length;
  return 1;  // content_decay and unknown types
}

// ── Public adapters ────────────────────────────────────────────────────────

/**
 * Normalize a `client_action` row into a `NormalizedDecision` for `<DecisionCard>`.
 *
 * `isSingleAction` is true only for `content_decay` — those render inline
 * with approve/flag buttons; all other types open `<DecisionDetailModal>`.
 */
export function normalizeClientAction(action: ClientAction): NormalizedDecision {
  return {
    id: `ca-${action.id}`,
    source: 'client_action',
    sourceId: action.id,
    title: action.title,
    summary: action.summary,
    priority: action.priority,
    itemCount: itemCountForAction(action),
    isSingleAction: action.sourceType === 'content_decay',
    badge: CLIENT_ACTION_BADGES[action.sourceType] ?? action.sourceType.replace(/_/g, ' '),
    createdAt: action.createdAt,
  };
}

/**
 * Normalize an `approval_batch` row into a `NormalizedDecision` for `<DecisionCard>`.
 *
 * Approval batches never have isSingleAction=true — they always open the
 * full-screen `<DecisionDetailModal>` regardless of item count.
 */
export function normalizeApprovalBatch(batch: ApprovalBatch): NormalizedDecision {
  return {
    id: `ab-${batch.id}`,
    source: 'approval_batch',
    sourceId: batch.id,
    title: batch.name,
    summary: `${batch.items.length} change${batch.items.length !== 1 ? 's' : ''} ready for your approval`,
    priority: undefined,
    itemCount: batch.items.length,
    isSingleAction: false,
    badge: badgeForBatch(batch.name),
    createdAt: batch.createdAt,
  };
}
