import type { ClientAction, ClientActionSourceType } from '../../shared/types/client-actions.js';
import type { ApprovalBatch } from '../../shared/types/approvals.js';
import type { DecisionKind, NormalizedDecision } from '../../shared/types/decision.js';
import type { ClientDeliverable, DeliverableType } from '../../shared/types/client-deliverable.js';

// ── Badge labels ───────────────────────────────────────────────────────────

const CLIENT_ACTION_BADGES: Record<string, string> = {
  aeo_change:        'AEO',
  internal_link:     'Internal Links',
  redirect_proposal: 'Redirects',
  content_decay:     'Content',
  keyword_strategy:  'Keywords',   // deprecated; archived rows only
};

export function clientActionSourceLabel(sourceType: ClientActionSourceType | string): string {
  return CLIENT_ACTION_BADGES[sourceType] ?? 'SEO Update';
}

/**
 * Infer a short human badge from an approval_batch name.
 * Batch names are generated by admin tools: "SEO Editor — N pages",
 * "Schema — N pages", "CMS Editor — collection".
 */
export function badgeForBatch(name: string): string {
  const lower = name.toLowerCase();
  if (lower.startsWith('schema')) return 'Schema';
  if (lower.startsWith('cms')) return 'CMS';
  if (lower.startsWith('seo editor') || lower.startsWith('seo')) return 'SEO Editor';
  if (lower.startsWith('audit')) return 'Audit';
  return 'SEO';   // fallback
}

// ── Item count helpers ────────────────────────────────────────────────────

/**
 * For client_actions, itemCount reflects the number of individual changes
 * inside the payload. Falls back to 1 (the action itself is the single item).
 */
function itemCountForAction(action: ClientAction): number {
  const p = action.payload as Record<string, unknown>;
  if (Array.isArray(p?.diffs)) return (p.diffs as unknown[]).length;
  if (Array.isArray(p?.suggestions)) return (p.suggestions as unknown[]).length;
  if (Array.isArray(p?.redirects)) return (p.redirects as unknown[]).length;
  return 1;  // content_decay and unknown types
}

// ── Public adapters ────────────────────────────────────────────────────────

/**
 * Normalize a `client_action` row into a `NormalizedDecision` for `<DecisionCard>`.
 *
 * `isSingleAction` is true only for `content_decay` — those render inline
 * with approve/flag buttons; all other types open `<DecisionDetailModal>`.
 */
export function normalizeClientAction(action: ClientAction): NormalizedDecision {
  // content_decay → inline single-action ('decision' kind); all others open the modal ('batch').
  const kind: DecisionKind = action.sourceType === 'content_decay' ? 'decision' : 'batch';
  return {
    id: `ca-${action.id}`,
    source: 'client_action',
    sourceId: action.id,
    title: action.title,
    summary: action.summary,
    priority: action.priority,
    itemCount: itemCountForAction(action),
    kind,
    isSingleAction: kind === 'decision',
    badge: clientActionSourceLabel(action.sourceType),
    createdAt: action.createdAt,
  };
}

/**
 * Normalize an `approval_batch` row into a `NormalizedDecision` for `<DecisionCard>`.
 *
 * Approval batches never have isSingleAction=true — they always open the
 * full-screen `<DecisionDetailModal>` regardless of item count.
 */
export function normalizeApprovalBatch(batch: ApprovalBatch): NormalizedDecision {
  return {
    id: `ab-${batch.id}`,
    source: 'approval_batch',
    sourceId: batch.id,
    title: batch.name,
    summary: `${batch.items.length} change${batch.items.length !== 1 ? 's' : ''} ready for your approval`,
    priority: undefined,
    itemCount: batch.items.length,
    // Approval batches always open the full-screen modal (never inline) regardless of item count.
    kind: 'batch',
    isSingleAction: false,
    badge: badgeForBatch(batch.name),
    createdAt: batch.createdAt,
  };
}

// ── Unified ClientDeliverable adapter (PR-2a) ───────────────────────────────

/** Short human badge for each unified deliverable type — shown in the inbox card/strip. */
const DELIVERABLE_TYPE_BADGES: Record<DeliverableType, string> = {
  seo_edit:              'SEO Editor',
  audit_issue:           'Audit',
  schema_item:           'Schema',
  schema_plan:           'Schema',
  redirect:              'Redirects',
  internal_link:         'Internal Links',
  aeo_change:            'AEO',
  content_decay:         'Content',
  content_plan_sample:   'Content Plan',
  content_plan_template: 'Content Plan',
  work_order:            'Work Order',
  briefing:              'Briefing',
  copy_section:          'Copy',
  content_request:       'Content',
};

export function deliverableTypeBadge(type: DeliverableType | string): string {
  return DELIVERABLE_TYPE_BADGES[type as DeliverableType] ?? 'Update';
}

/**
 * The PROJECTED (D-hybrid) deliverable types — `copy_section` and `content_request` — have NO
 * physical `client_deliverable` row; their ids are `copy:<entryId>` / `content_request:<id>` and
 * they are projected at read time from their source tables (design §13-D1). They are responded to
 * via their own bespoke routes (copy-pipeline / content-briefs), NOT the unified `/respond`
 * endpoint (which does a PK lookup on the physical table and 404s for a projected id). The unified
 * inbox uses this predicate to render a read-only "Review →" deep-link for projected items instead
 * of wiring the uniform Approve / Request-changes / Decline verbs to `/respond`.
 */
const PROJECTED_DELIVERABLE_TYPES: ReadonlySet<DeliverableType> = new Set<DeliverableType>([
  'copy_section',
  'content_request',
]);

export function isProjectedDeliverable(type: DeliverableType | string): boolean {
  return PROJECTED_DELIVERABLE_TYPES.has(type as DeliverableType);
}

/**
 * The client_action-family types whose sub-items ride in `payload.items` (the multi-field
 * redirect / internal-link / AEO diff arrays), NOT the typed `_item` columns (design §4.1).
 * For these, `itemCount` must count `payload.items.length`, not `items[].length` (which is empty).
 */
const PAYLOAD_ITEMS_DELIVERABLE_TYPES: ReadonlySet<DeliverableType> = new Set<DeliverableType>([
  'redirect',
  'internal_link',
  'aeo_change',
]);

/**
 * Count the substantive sub-items of a unified deliverable for the inbox card's "View N →" affordance.
 *
 * Two storage shapes (design §4.1):
 *  - approval/SEO/schema family → typed `_item` rows in `items[]`.
 *  - client_action family (redirect/internal_link/aeo_change) → sub-items in `payload.items`
 *    (the `_item` columns stay empty for this family), so `items[].length` would wrongly be 0
 *    and fall back to 1. Count `payload.items.length` instead.
 *
 * Falls back to 1 (the deliverable is itself a single item, e.g. content_decay).
 */
function itemCountForDeliverable(d: ClientDeliverable): number {
  if (PAYLOAD_ITEMS_DELIVERABLE_TYPES.has(d.type)) {
    const payloadItems = (d.payload as Record<string, unknown>)?.items;
    if (Array.isArray(payloadItems) && payloadItems.length > 0) return payloadItems.length;
    return 1;
  }
  return d.items && d.items.length > 0 ? d.items.length : 1;
}

/**
 * The single canonical approve-CTA label for the unified inbox (item 5 — vocab reconcile). Every
 * approve affordance in the unified inbox (InlineApprovalCard, DeliverableDetailModal, DecisionCard
 * uniform mode) reads the SAME way:
 *   - no subset held  → "Looks good — implement N →"
 *   - subset held     → "Looks good — implement N of M →"  (N = items being implemented now, M = total)
 *   - submitting      → "Submitting…"
 * `heldCount` is the number of items flagged/held back (0 when nothing is held). This keeps the
 * "N of M" held-count where a subset is held, per the owner's vocab reconcile.
 */
export function approveCtaLabel(totalItems: number, heldCount = 0, submitting = false): string {
  if (submitting) return 'Submitting…';
  const implementing = Math.max(totalItems - heldCount, 0);
  return heldCount > 0
    ? `Looks good — implement ${implementing} of ${totalItems} →`
    : `Looks good — implement ${totalItems} →`;
}

/**
 * Normalize a unified `ClientDeliverable` into a `NormalizedDecision` (design §5).
 *
 * `kind` is carried straight through from the deliverable; `isSingleAction` is DERIVED from
 * `kind === 'decision'` so the inline-vs-modal affordance is identical to the legacy path.
 * `itemCount` reflects the substantive sub-items: the typed `_item` rows for the approval/SEO/
 * schema family, or `payload.items` for the client_action family (redirect/internal_link/aeo_change)
 * whose sub-items ride in payload (design §4.1), else 1. `sentAt` carries the staleness clock so
 * the inbox can show the send age. `items` + `payload` are carried through so R3 can render the
 * per-item review/diff surface without a second fetch (additive — legacy adapters omit them).
 */
export function normalizeDeliverable(d: ClientDeliverable): NormalizedDecision {
  return {
    id: `cd-${d.id}`,
    source: 'deliverable',
    sourceId: d.id,
    title: d.title,
    summary: d.summary ?? '',
    priority: undefined,
    itemCount: itemCountForDeliverable(d),
    kind: d.kind,
    isSingleAction: d.kind === 'decision',
    badge: deliverableTypeBadge(d.type),
    createdAt: d.createdAt,
    sentAt: d.sentAt,
    items: d.items,
    payload: d.payload,
  };
}
