-- 043-intelligence-caching-layer.sql
-- Unified Workspace Intelligence Layer — Phase 1 foundation tables
-- Spec: docs/superpowers/specs/unified-workspace-intelligence.md §15

-- Add bridge source tagging to analytics_insights (for rollback auditability, §19)
-- Nullable — existing rows get NULL, new bridge-written rows get 'bridge_N_name'
ALTER TABLE analytics_insights ADD COLUMN resolution_source TEXT;

-- Workspace-level intelligence sub-caches (for surgical invalidation)
CREATE TABLE IF NOT EXISTS intelligence_sub_cache (
  workspace_id TEXT NOT NULL,
  cache_key TEXT NOT NULL,
  ttl_seconds INTEGER NOT NULL,
  cached_at TEXT NOT NULL DEFAULT (datetime('now')),
  invalidated_at TEXT,
  data TEXT NOT NULL,
  PRIMARY KEY (workspace_id, cache_key),
  FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
);

-- Content pipeline summary cache (pre-computed counts)
CREATE TABLE IF NOT EXISTS content_pipeline_cache (
  workspace_id TEXT PRIMARY KEY,
  summary_json TEXT NOT NULL DEFAULT '{}',
  cached_at TEXT NOT NULL DEFAULT (datetime('now')),
  invalidated_at TEXT,
  FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
);

-- Suggested briefs (auto-generated by Bridge #2 in Phase 2: decay → brief)
-- Created now so the table exists; populated by Phase 2 bridges
CREATE TABLE IF NOT EXISTS suggested_briefs (
  id TEXT PRIMARY KEY,
  workspace_id TEXT NOT NULL,
  keyword TEXT NOT NULL,
  page_url TEXT,
  source TEXT NOT NULL DEFAULT 'content_decay',
  reason TEXT NOT NULL,
  priority TEXT NOT NULL DEFAULT 'medium',
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  resolved_at TEXT,
  snoozed_until TEXT,
  dismissed_keyword_hash TEXT,
  FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_suggested_briefs_workspace ON suggested_briefs(workspace_id, status);
