-- Preserve canonical/action metadata generated by keyword-strategy cannibalization analysis.

ALTER TABLE cannibalization_issues ADD COLUMN canonical_path TEXT;
ALTER TABLE cannibalization_issues ADD COLUMN canonical_url TEXT;
ALTER TABLE cannibalization_issues ADD COLUMN action TEXT;
