export type AIOperationProvider = 'openai' | 'anthropic';
export type AIOperationOutputMode = 'prose' | 'json';
export type AIOperationResearchMode = 'required' | 'optional' | 'forbidden';
export type AIOperationExecutionMode = 'sync-only' | 'background-only' | 'sync-or-background';
export type AIOperationRetryPolicy = 'none' | 'standard' | 'aggressive';
export type AIOperationTimeoutProfile = 'short' | 'standard' | 'long';

export interface AIOperationContract {
  id: string;
  domain: string;
  feature: string;
  providerIntent: AIOperationProvider | 'either';
  modelIntent: string;
  outputMode: AIOperationOutputMode;
  parserExpectation: string;
  researchMode: AIOperationResearchMode;
  executionMode: AIOperationExecutionMode;
  retryPolicy: AIOperationRetryPolicy;
  timeoutProfile: AIOperationTimeoutProfile;
  defaultProvider?: AIOperationProvider;
  defaultModel?: string;
  defaultResponseFormat?: { type: 'json_object' };
  defaultMaxRetries?: number;
  defaultTimeoutMs?: number;
  defaultResearchMode?: boolean;
}

export const AI_OPERATION_REGISTRY = {
  'content-brief-regenerate': {
    id: 'content-brief-regenerate',
    domain: 'content-pipeline',
    feature: 'content-brief-regenerate',
    providerIntent: 'openai',
    modelIntent: 'high-fidelity structured regeneration',
    outputMode: 'json',
    parserExpectation: 'parseAiJson(content-brief)',
    researchMode: 'required',
    executionMode: 'sync-or-background',
    retryPolicy: 'standard',
    timeoutProfile: 'long',
    defaultProvider: 'openai',
    defaultModel: 'gpt-5.4',
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 90_000,
    defaultResearchMode: true,
  },
  'schema-plan': {
    id: 'schema-plan',
    domain: 'schema',
    feature: 'schema-plan',
    providerIntent: 'openai',
    modelIntent: 'high-precision role classification',
    outputMode: 'json',
    parserExpectation: 'strict JSON.parse + schema-plan guards',
    researchMode: 'forbidden',
    executionMode: 'sync-or-background',
    retryPolicy: 'standard',
    timeoutProfile: 'standard',
    defaultProvider: 'openai',
    defaultModel: 'gpt-5.4-mini',
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 90_000,
    defaultResearchMode: false,
  },
  'client-search-chat': {
    id: 'client-search-chat',
    domain: 'client-portal',
    feature: 'client-search-chat',
    providerIntent: 'openai',
    modelIntent: 'client conversational SEO advisor',
    outputMode: 'prose',
    parserExpectation: 'plain assistant text',
    researchMode: 'optional',
    executionMode: 'sync-only',
    retryPolicy: 'standard',
    timeoutProfile: 'standard',
    defaultProvider: 'openai',
    defaultModel: 'gpt-5.4',
    defaultMaxRetries: 3,
    defaultTimeoutMs: 60_000,
    defaultResearchMode: false,
  },
  'content-decay': {
    id: 'content-decay',
    domain: 'content-pipeline',
    feature: 'content-decay',
    providerIntent: 'openai',
    modelIntent: 'concise optimization recommendations',
    outputMode: 'prose',
    parserExpectation: 'plain recommendation bullets',
    researchMode: 'optional',
    executionMode: 'sync-or-background',
    retryPolicy: 'standard',
    timeoutProfile: 'standard',
    defaultProvider: 'openai',
    defaultModel: 'gpt-5.4-mini',
    defaultMaxRetries: 3,
    defaultTimeoutMs: 60_000,
    defaultResearchMode: false,
  },
  'content-post-seo-meta': {
    id: 'content-post-seo-meta',
    domain: 'content-pipeline',
    feature: 'content-post-seo-meta',
    providerIntent: 'openai',
    modelIntent: 'structured SEO metadata synthesis from final post content',
    outputMode: 'json',
    parserExpectation: 'parseStructuredAIOutput(seo-meta)',
    researchMode: 'forbidden',
    executionMode: 'sync-or-background',
    retryPolicy: 'standard',
    timeoutProfile: 'short',
    defaultProvider: 'openai',
    defaultModel: 'gpt-5.4',
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 60_000,
    defaultResearchMode: false,
  },
  'content-post-feedback-fix': {
    id: 'content-post-feedback-fix',
    domain: 'content-pipeline',
    feature: 'content-post-feedback-fix',
    providerIntent: 'openai',
    modelIntent: 'targeted HTML post editing from operator feedback',
    outputMode: 'prose',
    parserExpectation: 'sanitizeRichText + field-targeted apply',
    researchMode: 'optional',
    executionMode: 'sync-only',
    retryPolicy: 'standard',
    timeoutProfile: 'standard',
    defaultProvider: 'openai',
    defaultModel: 'gpt-5.4',
    defaultMaxRetries: 3,
    defaultTimeoutMs: 60_000,
    defaultResearchMode: false,
  },
  'content-post-feedback-fix-structured': {
    id: 'content-post-feedback-fix-structured',
    domain: 'content-pipeline',
    feature: 'content-post-feedback-fix-structured',
    providerIntent: 'openai',
    modelIntent: 'structured JSON output for post/meta feedback edits',
    outputMode: 'json',
    parserExpectation: 'parseAIJson + zod schema validation',
    researchMode: 'optional',
    executionMode: 'sync-only',
    retryPolicy: 'standard',
    timeoutProfile: 'standard',
    defaultProvider: 'openai',
    defaultModel: 'gpt-5.4',
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 60_000,
    defaultResearchMode: false,
  },
  'content-post-unify': {
    id: 'content-post-unify',
    domain: 'content-pipeline',
    feature: 'content-post-unify',
    providerIntent: 'either',
    modelIntent: 'cohesion editing with structured HTML-part JSON output',
    outputMode: 'json',
    parserExpectation: 'parseStructuredAIOutput(content-post-unify)',
    researchMode: 'required',
    executionMode: 'sync-or-background',
    retryPolicy: 'standard',
    timeoutProfile: 'long',
    defaultProvider: 'openai',
    defaultModel: 'gpt-5.4',
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 90_000,
    defaultResearchMode: true,
  },
  'keyword-strategy': {
    id: 'keyword-strategy',
    domain: 'analytics-intelligence',
    feature: 'keyword-strategy',
    providerIntent: 'openai',
    modelIntent: 'strategy synthesis with deterministic JSON instructions',
    outputMode: 'json',
    parserExpectation: 'instruction-based JSON parse + stripCodeFences',
    researchMode: 'optional',
    executionMode: 'background-only',
    retryPolicy: 'standard',
    timeoutProfile: 'long',
    defaultProvider: 'openai',
    defaultModel: 'gpt-5.4-mini',
    defaultMaxRetries: 3,
    defaultTimeoutMs: 90_000,
    defaultResearchMode: false,
  },
  'keyword-page-assignment': {
    id: 'keyword-page-assignment',
    domain: 'analytics-intelligence',
    feature: 'keyword-page-assignment',
    providerIntent: 'openai',
    // SEO Generation Quality P3 — closed-set page→keyword assignment. The flag-ON
    // prompt diverges from the legacy keyword-strategy batch prompt: it enumerates a
    // closed candidate set with stable source-row ids + client-signal annotations and
    // instructs the AI to SELECT + JUSTIFY each pick by id (per
    // docs/rules/content-quality-grounding.md grounding contract). researchMode is ON
    // (defaultResearchMode:true) only on the flag-ON path; the flag-OFF legacy path
    // keeps the `keyword-strategy` op id verbatim (no research-mode divergence).
    modelIntent: 'closed-set page→keyword assignment with source-grounded selection',
    outputMode: 'json',
    parserExpectation: 'parseJsonSafe + zod, retry-once then deterministic backfill',
    researchMode: 'required',
    executionMode: 'background-only',
    retryPolicy: 'standard',
    timeoutProfile: 'long',
    defaultProvider: 'openai',
    defaultModel: 'gpt-5.4-mini',
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 90_000,
    defaultResearchMode: true,
  },
  'keyword-site-synthesis': {
    id: 'keyword-site-synthesis',
    domain: 'analytics-intelligence',
    feature: 'keyword-site-synthesis',
    providerIntent: 'openai',
    // SEO Generation Quality P3 — closed-set site-level synthesis (siteKeywords,
    // opportunities, contentGaps, quickWins). flag-ON-only prompt divergence (closed
    // candidate set + business-priorities context + select/justify by id) documented
    // here per the AI-operation-contracts rule; flag-OFF keeps the legacy `keyword-strategy`
    // master prompt + op id verbatim.
    modelIntent: 'closed-set site-level strategy synthesis with source-grounded selection',
    outputMode: 'json',
    parserExpectation: 'parseJsonSafe + zod, retry-once then deterministic backfill',
    researchMode: 'required',
    executionMode: 'background-only',
    retryPolicy: 'standard',
    timeoutProfile: 'long',
    defaultProvider: 'openai',
    defaultModel: 'gpt-5.4-mini',
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 90_000,
    defaultResearchMode: true,
  },
  'meeting-brief': {
    id: 'meeting-brief',
    domain: 'analytics-intelligence',
    feature: 'meeting-brief',
    providerIntent: 'openai',
    modelIntent: 'client-facing narrative brief with deterministic JSON shape',
    outputMode: 'json',
    parserExpectation: 'parseStructuredAIOutput(meeting-brief)',
    researchMode: 'forbidden',
    executionMode: 'sync-only',
    retryPolicy: 'standard',
    timeoutProfile: 'standard',
    defaultProvider: 'openai',
    defaultModel: 'gpt-5.4',
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 60_000,
    defaultResearchMode: false,
  },
  'knowledge-base-gen': {
    id: 'knowledge-base-gen',
    domain: 'platform-foundation',
    feature: 'knowledge-base-gen',
    providerIntent: 'openai',
    modelIntent: 'knowledge extraction summarization',
    outputMode: 'prose',
    parserExpectation: 'plain structured prose',
    researchMode: 'forbidden',
    executionMode: 'background-only',
    retryPolicy: 'standard',
    timeoutProfile: 'long',
    defaultProvider: 'openai',
    defaultModel: 'gpt-5.4',
    defaultMaxRetries: 3,
    defaultTimeoutMs: 90_000,
    defaultResearchMode: false,
  },
  'intelligence-profile-autofill': {
    id: 'intelligence-profile-autofill',
    domain: 'platform-foundation',
    feature: 'intelligence-profile-autofill',
    providerIntent: 'openai',
    modelIntent: 'small structured business-profile inference',
    outputMode: 'json',
    parserExpectation: 'parseStructuredAIOutput(intelligence-profile-autofill)',
    researchMode: 'forbidden',
    executionMode: 'sync-only',
    retryPolicy: 'standard',
    timeoutProfile: 'short',
    defaultProvider: 'openai',
    defaultModel: 'gpt-5.4-mini',
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 60_000,
    defaultResearchMode: false,
  },
  'brand-voice-gen': {
    id: 'brand-voice-gen',
    domain: 'brand-engine',
    feature: 'brand-voice-gen',
    providerIntent: 'openai',
    modelIntent: 'voice pattern extraction from site corpus',
    outputMode: 'prose',
    parserExpectation: 'plain structured prose',
    researchMode: 'forbidden',
    executionMode: 'background-only',
    retryPolicy: 'standard',
    timeoutProfile: 'long',
    defaultProvider: 'openai',
    defaultModel: 'gpt-5.4',
    defaultMaxRetries: 3,
    defaultTimeoutMs: 90_000,
    defaultResearchMode: false,
  },
  'voice-feedback-suggest': {
    id: 'voice-feedback-suggest',
    domain: 'brand-engine',
    feature: 'voice-feedback-suggest',
    providerIntent: 'openai',
    modelIntent: 'single-suggestion voice profile adjustment classifier',
    outputMode: 'json',
    parserExpectation: 'parseStructuredAIOutput(voice-feedback-suggest)',
    researchMode: 'forbidden',
    executionMode: 'sync-only',
    retryPolicy: 'standard',
    timeoutProfile: 'short',
    defaultProvider: 'openai',
    defaultModel: 'gpt-5.4-mini',
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 60_000,
    defaultResearchMode: false,
  },
  'voice-scoring': {
    id: 'voice-scoring',
    domain: 'brand-engine',
    feature: 'voice-scoring',
    providerIntent: 'openai',
    modelIntent: 'structured brand voice scoring and feedback',
    outputMode: 'json',
    parserExpectation: 'parseStructuredAIOutput(voice-scoring)',
    researchMode: 'forbidden',
    executionMode: 'sync-only',
    retryPolicy: 'standard',
    timeoutProfile: 'short',
    defaultProvider: 'openai',
    defaultModel: 'gpt-5.4',
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 60_000,
    defaultResearchMode: false,
  },
  'personas-gen': {
    id: 'personas-gen',
    domain: 'brand-engine',
    feature: 'personas-gen',
    providerIntent: 'openai',
    modelIntent: 'persona extraction JSON synthesis',
    outputMode: 'json',
    parserExpectation: 'JSON.parse + normalizePersonaResults',
    researchMode: 'forbidden',
    executionMode: 'background-only',
    retryPolicy: 'standard',
    timeoutProfile: 'long',
    defaultProvider: 'openai',
    defaultModel: 'gpt-5.4',
    defaultMaxRetries: 3,
    defaultTimeoutMs: 90_000,
    defaultResearchMode: false,
  },
  'content-brief-outline': {
    id: 'content-brief-outline',
    domain: 'content-pipeline',
    feature: 'content-brief-outline',
    providerIntent: 'openai',
    modelIntent: 'outline section array regeneration from feedback',
    outputMode: 'json',
    parserExpectation: 'parseContentBriefOutline (bare array, aiContentBriefOutlineSchema)',
    researchMode: 'optional',
    executionMode: 'sync-only',
    retryPolicy: 'standard',
    timeoutProfile: 'standard',
    defaultProvider: 'openai',
    defaultModel: 'gpt-5.4',
    defaultMaxRetries: 3,
    defaultTimeoutMs: 60_000,
    defaultResearchMode: true,
  },
  'aeo-page-review': {
    id: 'aeo-page-review',
    domain: 'content-pipeline',
    feature: 'aeo-page-review',
    providerIntent: 'openai',
    modelIntent: 'per-page AEO content change recommendations',
    outputMode: 'json',
    parserExpectation: 'parseAeoReview (aiAeoReviewSchema)',
    researchMode: 'optional',
    executionMode: 'sync-or-background',
    retryPolicy: 'standard',
    timeoutProfile: 'standard',
    defaultProvider: 'openai',
    defaultModel: 'gpt-5.4',
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 60_000,
    defaultResearchMode: true,
  },
  'diagnostic-root-causes': {
    id: 'diagnostic-root-causes',
    domain: 'analytics-intelligence',
    feature: 'diagnostic-root-causes',
    providerIntent: 'openai',
    modelIntent: 'anomaly root-cause synthesis with structured remediation plan',
    outputMode: 'json',
    parserExpectation: 'parseDiagnosticRootCauses (aiRootCauseAnalysisSchema)',
    researchMode: 'forbidden',
    executionMode: 'background-only',
    retryPolicy: 'standard',
    timeoutProfile: 'standard',
    defaultProvider: 'openai',
    defaultModel: 'gpt-5.4',
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 60_000,
    defaultResearchMode: false,
  },
  'schema-plan-generate': {
    id: 'schema-plan-generate',
    domain: 'schema',
    feature: 'schema-plan-generate',
    providerIntent: 'openai',
    modelIntent: 'page-role classification and canonical entity extraction for schema planning',
    outputMode: 'json',
    parserExpectation: 'parseSchemaPlan (aiSchemaPlanSchema)',
    researchMode: 'forbidden',
    executionMode: 'sync-or-background',
    retryPolicy: 'standard',
    timeoutProfile: 'standard',
    defaultProvider: 'openai',
    defaultModel: 'gpt-5.4-mini',
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 90_000,
    defaultResearchMode: false,
  },
} as const satisfies Record<string, AIOperationContract>;

export type AIOperationId = keyof typeof AI_OPERATION_REGISTRY;

export function isAIOperationId(value: string): value is AIOperationId {
  return Object.prototype.hasOwnProperty.call(AI_OPERATION_REGISTRY, value);
}

export function getAIOperationContract(operationId: AIOperationId): AIOperationContract {
  return AI_OPERATION_REGISTRY[operationId];
}
