import type { AICachePolicy } from '../shared/types/ai-execution.js';
import { MODEL_ROLES } from './model-manifest.js';

export type AIOperationProvider = 'openai' | 'anthropic';
export type AIOperationOutputMode = 'prose' | 'json';
export type AIOperationResearchMode = 'required' | 'optional' | 'forbidden';
export type AIOperationExecutionMode = 'sync-only' | 'background-only' | 'sync-or-background';
export type AIOperationRetryPolicy = 'none' | 'standard' | 'aggressive';
export type AIOperationTimeoutProfile = 'short' | 'standard' | 'long';

export interface AIOperationContract {
  id: string;
  domain: string;
  feature: string;
  providerIntent: AIOperationProvider | 'either';
  modelIntent: string;
  outputMode: AIOperationOutputMode;
  parserExpectation: string;
  researchMode: AIOperationResearchMode;
  executionMode: AIOperationExecutionMode;
  retryPolicy: AIOperationRetryPolicy;
  timeoutProfile: AIOperationTimeoutProfile;
  defaultProvider?: AIOperationProvider;
  defaultModel?: string;
  defaultResponseFormat?: { type: 'json_object' };
  defaultMaxRetries?: number;
  defaultTimeoutMs?: number;
  defaultResearchMode?: boolean;
}

export interface AIOperationRuntimeDefaults {
  feature: string;
  defaultProvider?: AIOperationProvider;
  defaultModel?: string;
  defaultResponseFormat?: { type: 'json_object' };
  defaultMaxRetries?: number;
  defaultTimeoutMs?: number;
  defaultResearchMode?: boolean;
  cachePolicy: AICachePolicy;
}

export type AIOperationPolicyMetadata = Pick<
  AIOperationContract,
  | 'id'
  | 'domain'
  | 'feature'
  | 'providerIntent'
  | 'modelIntent'
  | 'outputMode'
  | 'parserExpectation'
  | 'researchMode'
  | 'executionMode'
  | 'retryPolicy'
  | 'timeoutProfile'
>;

export const AI_OPERATION_REGISTRY = {
  'content-brief-generate': {
    id: 'content-brief-generate',
    domain: 'content-pipeline',
    feature: 'content-brief',
    providerIntent: 'openai',
    modelIntent: 'grounded structured content brief generation',
    outputMode: 'json',
    parserExpectation: 'parseContentBriefSchema',
    researchMode: 'required',
    executionMode: 'sync-or-background',
    retryPolicy: 'standard',
    timeoutProfile: 'long',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.structuredSynthesis,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 90_000,
    defaultResearchMode: true,
  },
  'content-brief-regenerate': {
    id: 'content-brief-regenerate',
    domain: 'content-pipeline',
    feature: 'content-brief-regenerate',
    providerIntent: 'openai',
    modelIntent: 'high-fidelity structured regeneration',
    outputMode: 'json',
    parserExpectation: 'parseAiJson(content-brief)',
    researchMode: 'required',
    executionMode: 'sync-or-background',
    retryPolicy: 'standard',
    timeoutProfile: 'long',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.structuredSynthesis,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 90_000,
    defaultResearchMode: true,
  },
  'schema-plan': {
    id: 'schema-plan',
    domain: 'schema',
    feature: 'schema-plan',
    providerIntent: 'openai',
    modelIntent: 'high-precision role classification',
    outputMode: 'json',
    parserExpectation: 'strict JSON.parse + schema-plan guards',
    researchMode: 'forbidden',
    executionMode: 'sync-or-background',
    retryPolicy: 'standard',
    timeoutProfile: 'standard',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.utilityExtraction,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 90_000,
    defaultResearchMode: false,
  },
  'client-search-chat': {
    id: 'client-search-chat',
    domain: 'client-portal',
    feature: 'client-search-chat',
    providerIntent: 'openai',
    modelIntent: 'client conversational SEO advisor',
    outputMode: 'prose',
    parserExpectation: 'plain assistant text',
    researchMode: 'optional',
    executionMode: 'sync-only',
    retryPolicy: 'standard',
    timeoutProfile: 'standard',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.structuredSynthesis,
    defaultMaxRetries: 3,
    defaultTimeoutMs: 60_000,
    defaultResearchMode: false,
  },
  'content-decay': {
    id: 'content-decay',
    domain: 'content-pipeline',
    feature: 'content-decay',
    providerIntent: 'openai',
    modelIntent: 'concise optimization recommendations',
    outputMode: 'prose',
    parserExpectation: 'plain recommendation bullets',
    researchMode: 'optional',
    executionMode: 'sync-or-background',
    retryPolicy: 'standard',
    timeoutProfile: 'standard',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.utilityExtraction,
    defaultMaxRetries: 3,
    defaultTimeoutMs: 60_000,
    defaultResearchMode: false,
  },
  'seo-metadata-variations': {
    id: 'seo-metadata-variations',
    domain: 'seo-health',
    feature: 'seo-metadata-variations',
    providerIntent: 'either',
    modelIntent: 'evidence-grounded creative SEO title and meta-description variations',
    outputMode: 'json',
    parserExpectation: 'parseStructuredAIOutput(seo-metadata-variations) + deterministic SEO limits',
    researchMode: 'required',
    executionMode: 'sync-or-background',
    retryPolicy: 'standard',
    timeoutProfile: 'long',
    defaultProvider: 'anthropic',
    defaultModel: MODEL_ROLES.creativeWriter,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 240_000,
    defaultResearchMode: true,
  },
  'seo-page-copy-set': {
    id: 'seo-page-copy-set',
    domain: 'seo-health',
    feature: 'seo-page-copy-set',
    providerIntent: 'either',
    modelIntent: 'evidence-grounded creative SEO title, description, H1, introduction, and internal-link suggestions',
    outputMode: 'json',
    parserExpectation: 'parseStructuredAIOutput(seo-page-copy-set) + verified internal-link filtering',
    researchMode: 'required',
    executionMode: 'sync-only',
    retryPolicy: 'standard',
    timeoutProfile: 'long',
    defaultProvider: 'anthropic',
    defaultModel: MODEL_ROLES.creativeWriter,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 240_000,
    defaultResearchMode: true,
  },
  'content-post-seo-meta': {
    id: 'content-post-seo-meta',
    domain: 'content-pipeline',
    feature: 'content-post-seo-meta',
    providerIntent: 'openai',
    modelIntent: 'structured SEO metadata synthesis from final post content',
    outputMode: 'json',
    parserExpectation: 'parseStructuredAIOutput(seo-meta)',
    researchMode: 'forbidden',
    executionMode: 'sync-or-background',
    retryPolicy: 'standard',
    timeoutProfile: 'short',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.structuredSynthesis,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 60_000,
    defaultResearchMode: false,
  },
  'content-post-introduction': {
    id: 'content-post-introduction',
    domain: 'content-pipeline',
    feature: 'content-post-intro',
    providerIntent: 'either',
    modelIntent: 'grounded creative post introduction HTML',
    outputMode: 'prose',
    parserExpectation: 'clean HTML introduction',
    researchMode: 'required',
    executionMode: 'sync-or-background',
    retryPolicy: 'standard',
    timeoutProfile: 'long',
    defaultProvider: 'anthropic',
    defaultModel: MODEL_ROLES.creativeWriter,
    defaultMaxRetries: 3,
    // Opus 4.8 at high effort runs longer than the Sonnet-era 90s budget; a
    // timeout would convert a slow success into a duplicate paid attempt.
    defaultTimeoutMs: 240_000,
    defaultResearchMode: true,
  },
  'content-post-section': {
    id: 'content-post-section',
    domain: 'content-pipeline',
    feature: 'content-post-section',
    providerIntent: 'either',
    modelIntent: 'grounded creative post section HTML',
    outputMode: 'prose',
    parserExpectation: 'clean HTML section',
    researchMode: 'required',
    executionMode: 'sync-or-background',
    retryPolicy: 'standard',
    timeoutProfile: 'long',
    defaultProvider: 'anthropic',
    defaultModel: MODEL_ROLES.creativeWriter,
    defaultMaxRetries: 3,
    // Opus 4.8 at high effort runs longer than the Sonnet-era 90s budget; a
    // timeout would convert a slow success into a duplicate paid attempt.
    defaultTimeoutMs: 240_000,
    defaultResearchMode: true,
  },
  'content-post-conclusion': {
    id: 'content-post-conclusion',
    domain: 'content-pipeline',
    feature: 'content-post-conclusion',
    providerIntent: 'either',
    modelIntent: 'grounded creative post conclusion HTML',
    outputMode: 'prose',
    parserExpectation: 'clean HTML conclusion',
    researchMode: 'required',
    executionMode: 'sync-or-background',
    retryPolicy: 'standard',
    timeoutProfile: 'long',
    defaultProvider: 'anthropic',
    defaultModel: MODEL_ROLES.creativeWriter,
    defaultMaxRetries: 3,
    // Opus 4.8 at high effort runs longer than the Sonnet-era 90s budget; a
    // timeout would convert a slow success into a duplicate paid attempt.
    defaultTimeoutMs: 240_000,
    defaultResearchMode: true,
  },
  'content-post-review': {
    id: 'content-post-review',
    domain: 'content-pipeline',
    feature: 'content-review',
    providerIntent: 'openai',
    modelIntent: 'grounded structured post QA review',
    outputMode: 'json',
    parserExpectation: 'parseAIJson + aiReviewResponseSchema',
    researchMode: 'required',
    executionMode: 'background-only',
    retryPolicy: 'standard',
    timeoutProfile: 'standard',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.utilityExtraction,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 60_000,
    defaultResearchMode: true,
  },
  'content-post-feedback-fix': {
    id: 'content-post-feedback-fix',
    domain: 'content-pipeline',
    feature: 'content-post-feedback-fix',
    providerIntent: 'openai',
    modelIntent: 'targeted HTML post editing from operator feedback',
    outputMode: 'prose',
    parserExpectation: 'sanitizeRichText + field-targeted apply',
    researchMode: 'optional',
    executionMode: 'sync-only',
    retryPolicy: 'standard',
    timeoutProfile: 'standard',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.structuredSynthesis,
    defaultMaxRetries: 3,
    defaultTimeoutMs: 60_000,
    defaultResearchMode: false,
  },
  'content-post-feedback-fix-structured': {
    id: 'content-post-feedback-fix-structured',
    domain: 'content-pipeline',
    feature: 'content-post-feedback-fix-structured',
    providerIntent: 'openai',
    modelIntent: 'structured JSON output for post/meta feedback edits',
    outputMode: 'json',
    parserExpectation: 'parseAIJson + zod schema validation',
    researchMode: 'optional',
    executionMode: 'sync-only',
    retryPolicy: 'standard',
    timeoutProfile: 'standard',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.structuredSynthesis,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 60_000,
    defaultResearchMode: false,
  },
  'content-matrix-item-audit': {
    id: 'content-matrix-item-audit',
    domain: 'content-pipeline',
    feature: 'content-matrix-item-audit',
    providerIntent: 'openai',
    modelIntent: 'structured voice, persona, SEO, coherence, and grounding audit for one matrix page',
    outputMode: 'json',
    parserExpectation: 'parseStructuredAIOutput(content-matrix-item-audit)',
    researchMode: 'required',
    executionMode: 'background-only',
    retryPolicy: 'none',
    timeoutProfile: 'long',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.structuredSynthesis,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 0,
    defaultTimeoutMs: 90_000,
    defaultResearchMode: true,
  },
  'content-matrix-item-revise': {
    id: 'content-matrix-item-revise',
    domain: 'content-pipeline',
    feature: 'content-matrix-item-revise',
    providerIntent: 'either',
    modelIntent: 'bounded structured revision on the same active provider/model that generated the accepted prose',
    outputMode: 'json',
    parserExpectation: 'parseStructuredAIOutput(content-matrix-item-revise) + exact block census',
    researchMode: 'required',
    executionMode: 'background-only',
    retryPolicy: 'none',
    timeoutProfile: 'long',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.structuredSynthesis,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 0,
    defaultTimeoutMs: 90_000,
    defaultResearchMode: true,
  },
  'content-matrix-set-audit': {
    id: 'content-matrix-set-audit',
    domain: 'content-pipeline',
    feature: 'content-matrix-set-audit',
    providerIntent: 'openai',
    modelIntent: 'structured cross-page consistency and substantive-uniqueness audit',
    outputMode: 'json',
    parserExpectation: 'parseStructuredAIOutput(content-matrix-set-audit)',
    researchMode: 'required',
    executionMode: 'background-only',
    retryPolicy: 'none',
    timeoutProfile: 'long',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.structuredSynthesis,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 0,
    defaultTimeoutMs: 90_000,
    defaultResearchMode: true,
  },
  'gbp-review-response-draft': {
    id: 'gbp-review-response-draft',
    domain: 'integrations',
    feature: 'gbp-review-response-draft',
    providerIntent: 'openai',
    modelIntent: 'plain-text public review response drafting',
    outputMode: 'json',
    parserExpectation: 'parseAIJson + zod schema validation',
    researchMode: 'forbidden',
    executionMode: 'sync-only',
    retryPolicy: 'standard',
    timeoutProfile: 'short',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.structuredSynthesis,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 2,
    defaultTimeoutMs: 45_000,
    defaultResearchMode: false,
  },
  'content-post-unify': {
    id: 'content-post-unify',
    domain: 'content-pipeline',
    feature: 'content-post-unify',
    providerIntent: 'either',
    modelIntent: 'cohesion editing with structured HTML-part JSON output',
    outputMode: 'json',
    parserExpectation: 'parseStructuredAIOutput(content-post-unify)',
    researchMode: 'required',
    executionMode: 'sync-or-background',
    retryPolicy: 'standard',
    timeoutProfile: 'long',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.structuredSynthesis,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 90_000,
    defaultResearchMode: true,
  },
  'copy-generation': {
    id: 'copy-generation',
    domain: 'content-pipeline',
    feature: 'copy-generation',
    providerIntent: 'anthropic',
    modelIntent: 'full-page structured website copy generation',
    outputMode: 'json',
    parserExpectation: 'parseGeneratedPageCopy (aiGeneratedPageCopySchema)',
    researchMode: 'optional',
    executionMode: 'background-only',
    retryPolicy: 'standard',
    timeoutProfile: 'long',
    defaultProvider: 'anthropic',
    defaultModel: MODEL_ROLES.creativeWriter,
    defaultMaxRetries: 3,
    // Opus 4.8 at high effort runs longer than the Sonnet-era 90s budget; a
    // timeout would convert a slow success into a duplicate paid attempt.
    defaultTimeoutMs: 240_000,
    defaultResearchMode: false,
  },
  'copy-regeneration': {
    id: 'copy-regeneration',
    domain: 'content-pipeline',
    feature: 'copy-regeneration',
    providerIntent: 'anthropic',
    modelIntent: 'single-section structured website copy regeneration',
    outputMode: 'json',
    parserExpectation: 'parseRegeneratedSectionCopy (aiRegeneratedSectionCopySchema)',
    researchMode: 'optional',
    executionMode: 'sync-only',
    retryPolicy: 'standard',
    timeoutProfile: 'standard',
    defaultProvider: 'anthropic',
    defaultModel: MODEL_ROLES.creativeWriter,
    defaultMaxRetries: 3,
    // Sync single-section regeneration: modest Opus headroom without holding
    // the HTTP request open for the full background-tier budget.
    defaultTimeoutMs: 120_000,
    defaultResearchMode: false,
  },
  'content-publish-field-mapping': {
    id: 'content-publish-field-mapping',
    domain: 'content-pipeline',
    feature: 'suggest-field-mapping',
    providerIntent: 'openai',
    modelIntent: 'Webflow collection field mapping suggestion',
    outputMode: 'json',
    parserExpectation: 'parseWebflowFieldMapping (aiWebflowFieldMappingSchema) + collection slug allowlist',
    researchMode: 'forbidden',
    executionMode: 'sync-only',
    retryPolicy: 'standard',
    timeoutProfile: 'short',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.utilityExtraction,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 60_000,
    defaultResearchMode: false,
  },
  'keyword-strategy': {
    id: 'keyword-strategy',
    domain: 'analytics-intelligence',
    feature: 'keyword-strategy',
    providerIntent: 'openai',
    modelIntent: 'strategy synthesis with deterministic JSON instructions',
    outputMode: 'json',
    parserExpectation: 'instruction-based JSON parse + stripCodeFences',
    researchMode: 'optional',
    executionMode: 'background-only',
    retryPolicy: 'standard',
    timeoutProfile: 'long',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.utilityExtraction,
    defaultMaxRetries: 3,
    defaultTimeoutMs: 90_000,
    defaultResearchMode: false,
  },
  'keyword-page-assignment': {
    id: 'keyword-page-assignment',
    domain: 'analytics-intelligence',
    feature: 'keyword-page-assignment',
    providerIntent: 'openai',
    // SEO Generation Quality P3 — closed-set page→keyword assignment. The flag-ON
    // prompt diverges from the legacy keyword-strategy batch prompt: it enumerates a
    // closed candidate set with stable source-row ids + client-signal annotations and
    // instructs the AI to SELECT + JUSTIFY each pick by id (per
    // docs/rules/content-quality-grounding.md grounding contract). researchMode is ON
    // (defaultResearchMode:true) only on the flag-ON path; the flag-OFF legacy path
    // keeps the `keyword-strategy` op id verbatim (no research-mode divergence).
    modelIntent: 'closed-set page→keyword assignment with source-grounded selection',
    outputMode: 'json',
    parserExpectation: 'parseJsonSafe + zod, retry-once then deterministic backfill',
    researchMode: 'required',
    executionMode: 'background-only',
    retryPolicy: 'standard',
    timeoutProfile: 'long',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.utilityExtraction,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 90_000,
    defaultResearchMode: true,
  },
  'keyword-site-synthesis': {
    id: 'keyword-site-synthesis',
    domain: 'analytics-intelligence',
    feature: 'keyword-site-synthesis',
    providerIntent: 'openai',
    // SEO Generation Quality P3 — closed-set site-level synthesis (siteKeywords,
    // opportunities, contentGaps, quickWins). flag-ON-only prompt divergence (closed
    // candidate set + business-priorities context + select/justify by id) documented
    // here per the AI-operation-contracts rule; flag-OFF keeps the legacy `keyword-strategy`
    // master prompt + op id verbatim.
    //
    // F1 (#6) — MODEL UPGRADE: this is the single highest-leverage AI call in the
    // platform (it produces the whole site-level strategy). Upgraded from the
    // utility tier to the full structured-synthesis tier; the call sites raise
    // maxTokens from 3000 to 4500 to fit the richer closed-set selection +
    // justification output. The background-only execution mode and the `long`
    // timeout already accommodate the bigger model — synthesis only ever runs
    // inside the keyword-strategy generation job, never on a sync request. The
    // closed-set candidate pool + 3-stage sanitizer contracts are unchanged.
    modelIntent: 'closed-set site-level strategy synthesis with source-grounded selection (highest-leverage call → full synthesis tier)',
    outputMode: 'json',
    parserExpectation: 'parseJsonSafe + zod, retry-once then deterministic backfill',
    researchMode: 'required',
    executionMode: 'background-only',
    retryPolicy: 'standard',
    timeoutProfile: 'long',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.structuredSynthesis,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 90_000,
    defaultResearchMode: true,
  },
  'blueprint-generation': {
    id: 'blueprint-generation',
    domain: 'strategy',
    feature: 'blueprint-generation',
    providerIntent: 'anthropic',
    modelIntent: 'site blueprint page strategy with strict array schema',
    outputMode: 'json',
    parserExpectation: 'parseBlueprintGenerationOutput (zod array validation before DB writes)',
    researchMode: 'optional',
    executionMode: 'sync-or-background',
    retryPolicy: 'standard',
    timeoutProfile: 'long',
    defaultProvider: 'anthropic',
    defaultModel: MODEL_ROLES.creativeWriter,
    defaultMaxRetries: 3,
    // Opus 4.8 at high effort runs longer than the Sonnet-era 90s budget; a
    // timeout would convert a slow success into a duplicate paid attempt.
    defaultTimeoutMs: 240_000,
    defaultResearchMode: true,
  },
  'keyword-recommendation-rank': {
    id: 'keyword-recommendation-rank',
    domain: 'analytics-intelligence',
    feature: 'keyword-recommendations',
    providerIntent: 'openai',
    modelIntent: 'same-candidate-set keyword ranking',
    outputMode: 'json',
    parserExpectation: 'parseKeywordRankingOutput ({ keywords: string[] })',
    researchMode: 'forbidden',
    executionMode: 'sync-only',
    retryPolicy: 'standard',
    timeoutProfile: 'short',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.utilityExtraction,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 60_000,
    defaultResearchMode: false,
  },
  'keyword-topic-clusters': {
    id: 'keyword-topic-clusters',
    domain: 'analytics-intelligence',
    feature: 'keyword-topic-clusters',
    providerIntent: 'openai',
    modelIntent: 'topical authority cluster grouping from a closed keyword pool',
    outputMode: 'json',
    parserExpectation: 'parseTopicClusterOutput ({ clusters: [...] } object validation, skip malformed items)',
    researchMode: 'optional',
    executionMode: 'background-only',
    retryPolicy: 'standard',
    timeoutProfile: 'standard',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.utilityExtraction,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 90_000,
    defaultResearchMode: true,
  },
  'strategy-pov': {
    id: 'strategy-pov',
    domain: 'analytics-intelligence',
    feature: 'strategy-pov',
    providerIntent: 'openai',
    modelIntent: 'system-drafted curated point-of-view (narrated situation + lead move + wins/flags) over the curated rec set; deterministic JSON shape',
    outputMode: 'json',
    parserExpectation: 'parseStructuredAIOutput(strategy-pov)',
    researchMode: 'forbidden',
    executionMode: 'sync-only',
    retryPolicy: 'standard',
    timeoutProfile: 'standard',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.structuredSynthesis,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 60_000,
    defaultResearchMode: false,
  },
  'knowledge-base-gen': {
    id: 'knowledge-base-gen',
    domain: 'platform-foundation',
    feature: 'knowledge-base-gen',
    providerIntent: 'openai',
    modelIntent: 'knowledge extraction summarization',
    outputMode: 'prose',
    parserExpectation: 'plain structured prose',
    researchMode: 'forbidden',
    executionMode: 'background-only',
    retryPolicy: 'standard',
    timeoutProfile: 'long',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.structuredSynthesis,
    defaultMaxRetries: 3,
    defaultTimeoutMs: 90_000,
    defaultResearchMode: false,
  },
  'intelligence-profile-autofill': {
    id: 'intelligence-profile-autofill',
    domain: 'platform-foundation',
    feature: 'intelligence-profile-autofill',
    providerIntent: 'openai',
    modelIntent: 'small structured business-profile inference',
    outputMode: 'json',
    parserExpectation: 'parseStructuredAIOutput(intelligence-profile-autofill)',
    researchMode: 'forbidden',
    executionMode: 'sync-only',
    retryPolicy: 'standard',
    timeoutProfile: 'short',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.utilityExtraction,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 60_000,
    defaultResearchMode: false,
  },
  'brandscript-import': {
    id: 'brandscript-import',
    domain: 'brand-engine',
    feature: 'brandscript-import',
    providerIntent: 'openai',
    modelIntent: 'structured brandscript extraction from an imported brand document',
    outputMode: 'json',
    parserExpectation: 'parseStructuredAIOutput(brandscript-import)',
    researchMode: 'forbidden',
    executionMode: 'sync-only',
    retryPolicy: 'standard',
    timeoutProfile: 'standard',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.utilityExtraction,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 60_000,
    defaultResearchMode: false,
  },
  'brandscript-complete': {
    id: 'brandscript-complete',
    domain: 'brand-engine',
    feature: 'brandscript-complete',
    providerIntent: 'either',
    modelIntent: 'complete every requested empty brandscript section with structured copy',
    outputMode: 'json',
    parserExpectation: 'parseStructuredAIOutput(brandscript-complete) + exact requested-title census',
    researchMode: 'forbidden',
    executionMode: 'sync-only',
    retryPolicy: 'standard',
    timeoutProfile: 'standard',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.structuredSynthesis,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 60_000,
    defaultResearchMode: false,
  },
  'voice-calibration': {
    id: 'voice-calibration',
    domain: 'brand-engine',
    feature: 'voice-calibration',
    providerIntent: 'either',
    modelIntent: 'exactly three structured on-brand calibration variations',
    outputMode: 'json',
    parserExpectation: 'parseStructuredAIOutput(voice-calibration)',
    researchMode: 'forbidden',
    executionMode: 'sync-only',
    retryPolicy: 'standard',
    timeoutProfile: 'standard',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.structuredSynthesis,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 60_000,
    defaultResearchMode: false,
  },
  'voice-refinement': {
    id: 'voice-refinement',
    domain: 'brand-engine',
    feature: 'voice-refinement',
    providerIntent: 'either',
    modelIntent: 'single structured refinement of an existing calibration variation',
    outputMode: 'json',
    parserExpectation: 'parseStructuredAIOutput(voice-refinement)',
    researchMode: 'forbidden',
    executionMode: 'sync-only',
    retryPolicy: 'standard',
    timeoutProfile: 'standard',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.structuredSynthesis,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 60_000,
    defaultResearchMode: false,
  },
  'discovery-extraction': {
    id: 'discovery-extraction',
    domain: 'brand-engine',
    feature: 'discovery-extraction',
    providerIntent: 'openai',
    modelIntent: 'typed brand voice and story extraction from a discovery source',
    outputMode: 'json',
    parserExpectation: 'parseStructuredAIOutput(discovery-extraction)',
    researchMode: 'forbidden',
    executionMode: 'sync-only',
    retryPolicy: 'standard',
    timeoutProfile: 'standard',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.utilityExtraction,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 60_000,
    defaultResearchMode: false,
  },
  'monthly-digest': {
    id: 'monthly-digest',
    domain: 'analytics-intelligence',
    feature: 'monthly-digest',
    providerIntent: 'openai',
    modelIntent: 'closed-world selection and ordering of server-authored current-month evidence clauses',
    outputMode: 'json',
    parserExpectation: 'parseStructuredAIOutput(monthly-digest-clause-selection)',
    researchMode: 'forbidden',
    executionMode: 'sync-only',
    retryPolicy: 'standard',
    timeoutProfile: 'short',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.utilityExtraction,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 45_000,
    defaultResearchMode: false,
  },
  'brand-voice-gen': {
    id: 'brand-voice-gen',
    domain: 'brand-engine',
    feature: 'brand-voice-gen',
    providerIntent: 'openai',
    modelIntent: 'voice pattern extraction from site corpus',
    outputMode: 'prose',
    parserExpectation: 'plain structured prose',
    researchMode: 'forbidden',
    executionMode: 'background-only',
    retryPolicy: 'standard',
    timeoutProfile: 'long',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.structuredSynthesis,
    defaultMaxRetries: 3,
    defaultTimeoutMs: 90_000,
    defaultResearchMode: false,
  },
  'brand-deliverable-generate': {
    id: 'brand-deliverable-generate',
    domain: 'brand-engine',
    feature: 'brand-deliverable-generate',
    providerIntent: 'either',
    modelIntent: 'grounded structured brand-foundation and deliverable generation',
    outputMode: 'json',
    parserExpectation: 'parseStructuredAIOutput(brand-deliverable-generate) + evidence-key resolution',
    researchMode: 'required',
    executionMode: 'background-only',
    retryPolicy: 'none',
    timeoutProfile: 'long',
    defaultProvider: 'anthropic',
    defaultModel: MODEL_ROLES.creativeWriter,
    defaultMaxRetries: 0,
    // Opus 4.8 at high effort runs longer than the Sonnet-era 90s budget; a
    // timeout would convert a slow success into a duplicate paid attempt.
    defaultTimeoutMs: 240_000,
    defaultResearchMode: true,
  },
  'brand-deliverable-refine': {
    id: 'brand-deliverable-refine',
    domain: 'brand-engine',
    feature: 'brand-deliverable-refine',
    providerIntent: 'either',
    modelIntent: 'review-directed structured brand deliverable refinement',
    outputMode: 'json',
    parserExpectation: 'parseStructuredAIOutput(brand-deliverable-refine) + evidence-key resolution',
    researchMode: 'required',
    executionMode: 'background-only',
    retryPolicy: 'none',
    timeoutProfile: 'long',
    defaultProvider: 'anthropic',
    defaultModel: MODEL_ROLES.creativeWriter,
    defaultMaxRetries: 0,
    // Opus 4.8 at high effort runs longer than the Sonnet-era 90s budget; a
    // timeout would convert a slow success into a duplicate paid attempt.
    defaultTimeoutMs: 240_000,
    defaultResearchMode: true,
  },
  'brand-deliverable-audit': {
    id: 'brand-deliverable-audit',
    domain: 'brand-engine',
    feature: 'brand-deliverable-audit',
    providerIntent: 'openai',
    modelIntent: 'cross-deliverable evidence, voice, persona, and contradiction audit',
    outputMode: 'json',
    parserExpectation: 'parseStructuredAIOutput(brand-deliverable-audit)',
    researchMode: 'required',
    executionMode: 'background-only',
    retryPolicy: 'none',
    timeoutProfile: 'long',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.creativeRecovery,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 0,
    defaultTimeoutMs: 90_000,
    defaultResearchMode: true,
  },
  'voice-feedback-suggest': {
    id: 'voice-feedback-suggest',
    domain: 'brand-engine',
    feature: 'voice-feedback-suggest',
    providerIntent: 'openai',
    modelIntent: 'single-suggestion voice profile adjustment classifier',
    outputMode: 'json',
    parserExpectation: 'parseStructuredAIOutput(voice-feedback-suggest)',
    researchMode: 'forbidden',
    executionMode: 'sync-only',
    retryPolicy: 'standard',
    timeoutProfile: 'short',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.utilityExtraction,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 60_000,
    defaultResearchMode: false,
  },
  'voice-scoring': {
    id: 'voice-scoring',
    domain: 'brand-engine',
    feature: 'voice-scoring',
    providerIntent: 'openai',
    modelIntent: 'structured brand voice scoring and feedback',
    outputMode: 'json',
    parserExpectation: 'parseStructuredAIOutput(voice-scoring)',
    researchMode: 'forbidden',
    executionMode: 'sync-only',
    retryPolicy: 'standard',
    timeoutProfile: 'short',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.structuredSynthesis,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 60_000,
    defaultResearchMode: false,
  },
  'personas-gen': {
    id: 'personas-gen',
    domain: 'brand-engine',
    feature: 'personas-gen',
    providerIntent: 'openai',
    modelIntent: 'persona extraction JSON synthesis',
    outputMode: 'json',
    parserExpectation: 'JSON.parse + normalizePersonaResults',
    researchMode: 'forbidden',
    executionMode: 'background-only',
    retryPolicy: 'standard',
    timeoutProfile: 'long',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.structuredSynthesis,
    defaultMaxRetries: 3,
    defaultTimeoutMs: 90_000,
    defaultResearchMode: false,
  },
  'content-brief-outline': {
    id: 'content-brief-outline',
    domain: 'content-pipeline',
    feature: 'content-brief-outline',
    providerIntent: 'openai',
    modelIntent: 'outline section array regeneration from feedback',
    outputMode: 'json',
    parserExpectation: 'parseContentBriefOutline (bare array, aiContentBriefOutlineSchema)',
    researchMode: 'optional',
    executionMode: 'sync-only',
    retryPolicy: 'standard',
    timeoutProfile: 'standard',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.structuredSynthesis,
    defaultMaxRetries: 3,
    defaultTimeoutMs: 60_000,
    defaultResearchMode: true,
  },
  'aeo-page-review': {
    id: 'aeo-page-review',
    domain: 'content-pipeline',
    feature: 'aeo-page-review',
    providerIntent: 'openai',
    modelIntent: 'per-page AEO content change recommendations',
    outputMode: 'json',
    parserExpectation: 'parseAeoReview (aiAeoReviewSchema)',
    researchMode: 'optional',
    executionMode: 'sync-or-background',
    retryPolicy: 'standard',
    timeoutProfile: 'standard',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.structuredSynthesis,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 60_000,
    defaultResearchMode: true,
  },
  'diagnostic-root-causes': {
    id: 'diagnostic-root-causes',
    domain: 'analytics-intelligence',
    feature: 'diagnostic-root-causes',
    providerIntent: 'openai',
    modelIntent: 'anomaly root-cause synthesis with structured remediation plan',
    outputMode: 'json',
    parserExpectation: 'parseDiagnosticRootCauses (aiRootCauseAnalysisSchema)',
    researchMode: 'forbidden',
    executionMode: 'background-only',
    retryPolicy: 'standard',
    timeoutProfile: 'standard',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.structuredSynthesis,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 60_000,
    defaultResearchMode: false,
  },
  'schema-plan-generate': {
    id: 'schema-plan-generate',
    domain: 'schema',
    feature: 'schema-plan-generate',
    providerIntent: 'openai',
    modelIntent: 'page-role classification and canonical entity extraction for schema planning',
    outputMode: 'json',
    parserExpectation: 'parseSchemaPlan (aiSchemaPlanSchema)',
    researchMode: 'forbidden',
    executionMode: 'sync-or-background',
    retryPolicy: 'standard',
    timeoutProfile: 'standard',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.utilityExtraction,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 3,
    defaultTimeoutMs: 90_000,
    defaultResearchMode: false,
  },
  'the-issue-lead-value-enrich': {
    id: 'the-issue-lead-value-enrich',
    domain: 'analytics-intelligence',
    feature: 'the-issue-lead-value-enrich',
    providerIntent: 'openai',
    // The Issue (Client) P0 — single AI op: a low-confidence per-workspace lead/customer-value
    // estimate used ONLY as the basis='ai_enriched' fallback when no client_provided/agency_estimate
    // value exists. The advisory estimate never persists itself; the admin confirms via the standard
    // workspace PATCH (basis stamped in code, not by the model). Segment derivation is P1.
    modelIntent: 'small structured per-workspace lead/customer-value estimate (advisory, lowest confidence)',
    outputMode: 'json',
    parserExpectation: 'parseAIJson + leadValueEnrichSchema.safeParse → null on failure',
    researchMode: 'forbidden',
    executionMode: 'sync-only',
    retryPolicy: 'standard',
    timeoutProfile: 'short',
    defaultProvider: 'openai',
    defaultModel: MODEL_ROLES.utilityExtraction,
    defaultResponseFormat: { type: 'json_object' },
    defaultMaxRetries: 2,
    defaultTimeoutMs: 20_000,
    defaultResearchMode: false,
  },
} as const satisfies Record<string, AIOperationContract>;

export type AIOperationId = keyof typeof AI_OPERATION_REGISTRY;

const AI_OPERATION_CACHE_POLICY_OVERRIDES: Partial<Record<AIOperationId, AICachePolicy>> = {
  'schema-plan': { mode: 'ttl', ttlMs: 5 * 60 * 1000 },
  'content-post-feedback-fix': { mode: 'none' },
  'brand-deliverable-generate': { mode: 'none' },
  'brand-deliverable-refine': { mode: 'none' },
  'brand-deliverable-audit': { mode: 'none' },
  'content-matrix-item-audit': { mode: 'none' },
  'content-matrix-item-revise': { mode: 'none' },
  'content-matrix-set-audit': { mode: 'none' },
};

export function getAIOperationCachePolicy(operationId: AIOperationId): AICachePolicy {
  return AI_OPERATION_CACHE_POLICY_OVERRIDES[operationId] ?? { mode: 'inflight' };
}

export function isAIOperationId(value: string): value is AIOperationId {
  return Object.prototype.hasOwnProperty.call(AI_OPERATION_REGISTRY, value);
}

export function getAIOperationContract(operationId: AIOperationId): AIOperationContract {
  return AI_OPERATION_REGISTRY[operationId];
}

export function getAIOperationRuntimeDefaults(operationId: AIOperationId): AIOperationRuntimeDefaults {
  const contract = getAIOperationContract(operationId);
  return {
    feature: contract.feature,
    defaultProvider: contract.defaultProvider,
    defaultModel: contract.defaultModel,
    defaultResponseFormat: contract.defaultResponseFormat,
    defaultMaxRetries: contract.defaultMaxRetries,
    defaultTimeoutMs: contract.defaultTimeoutMs,
    defaultResearchMode: contract.defaultResearchMode,
    cachePolicy: getAIOperationCachePolicy(operationId),
  };
}

export function getAIOperationPolicyMetadata(operationId: AIOperationId): AIOperationPolicyMetadata {
  const contract = getAIOperationContract(operationId);
  return {
    id: contract.id,
    domain: contract.domain,
    feature: contract.feature,
    providerIntent: contract.providerIntent,
    modelIntent: contract.modelIntent,
    outputMode: contract.outputMode,
    parserExpectation: contract.parserExpectation,
    researchMode: contract.researchMode,
    executionMode: contract.executionMode,
    retryPolicy: contract.retryPolicy,
    timeoutProfile: contract.timeoutProfile,
  };
}
