import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Target } from 'lucide-react';
import { AIContextIndicator, TabBar, ErrorState, ProgressIndicator, NextStepsCard, LoadingState, PageHeader, Icon } from './ui';
import { formatDate } from '../utils/formatDates';
import { kdColor } from './page-intelligence/pageIntelligenceDisplay';
import { KeywordStrategyGuide } from './strategy/KeywordStrategyGuide';
import { useKeywordStrategy } from '../hooks/admin';
import { useFeatureFlag } from '../hooks/useFeatureFlag';
import { RefreshOrderingPrompt } from './keyword-strategy/RefreshOrderingPrompt';
import { BacklinkProfile } from './strategy/BacklinkProfile';
import { CompetitiveIntel } from './strategy/CompetitiveIntel';
import { ContentGaps } from './strategy/ContentGaps';
import { QuickWins } from './strategy/QuickWins';
import { KeywordGaps } from './strategy/KeywordGaps';
import { LowHangingFruit } from './strategy/LowHangingFruit';
import { TopicClusters } from './strategy/TopicClusters';
import { CannibalizationAlert } from './ui/CannibalizationAlert';
import { StrategyDiff } from './strategy/StrategyDiff';
import { IntelligenceSignals } from './strategy/IntelligenceSignals';
import { LocalSeoVisibilityPanel } from './local-seo/LocalSeoVisibilityPanel';
import {
  useStrategyMetrics,
  useStrategySettings,
  useStrategyGeneration,
  useTrackKeyword,
  useKeywordFeedback,
  StrategyHeaderActions,
  StrategyFeedbackNudge,
  ClientKeywordFeedback,
  StrategySettings,
  StrategyStalenessNudges,
  StrategyEmptyState,
  StrategyStatGrid,
  RankingDistribution,
  SiteTargetKeywords,
  KeywordOpportunities,
  StrategyHowItWorks,
  StrategyBand,
  DecisionQueue,
  RequestedKeywordTriage,
  OpportunitiesList,
  DecayingPagesCard,
  LostQueryRecoveryCard,
  CannibalizationTriage,
  buildStrategySummaryLine,
} from './strategy';
import { adminPath } from '../routes';

interface Props {
  workspaceId: string;
  siteId?: string;
}

export function KeywordStrategyPanel({ workspaceId }: Props) {
  const navigate = useNavigate();
  const [strategyTab, setStrategyTab] = useState<'analysis' | 'guide'>('analysis');

  // Decision-first 3-band IA (Decide/Act/Reference). OFF = today's sequential layout, byte-identical.
  const decisionBandsEnabled = useFeatureFlag('strategy-decision-bands');

  // React Query hook replaces manual data fetching
  const { data: keywordData, isLoading: loading, isAuxLoading, isError: strategyFetchError, refetch: refetchStrategy } = useKeywordStrategy(workspaceId);
  const strategy = keywordData?.strategy || null;
  // A "real" strategy has been generated by the AI pipeline (non-null generatedAt).
  // The server may synthesize a shell { pageMap, generatedAt: null, siteKeywords: [], opportunities: [] }
  // when page_keywords rows exist but no strategy blob — that case must render as "no strategy yet"
  // in this component, while still exposing pageMap via Page Intelligence separately.
  const isRealStrategy = strategy?.generatedAt != null;
  const displayedSeoDataMode = strategy?.seoDataMode;

  // Local ↔ Strategy sync status — present when workspace posture is local or hybrid.
  const localSync = keywordData?.strategy?.strategyUx?.localSync;

  // ── Logic hooks (extracted from this orchestrator in Phase 0) ──
  // Settings starts collapsed only in the decision-bands layout; the legacy layout keeps it open.
  const settings = useStrategySettings(keywordData, strategy, workspaceId, decisionBandsEnabled);
  const generation = useStrategyGeneration({
    workspaceId,
    localSync,
    buildStrategyGenerationParams: settings.buildStrategyGenerationParams,
  });
  const tracking = useTrackKeyword(workspaceId);
  const feedback = useKeywordFeedback(workspaceId);
  const metrics = useStrategyMetrics(strategy, feedback.rows, isRealStrategy);

  // intentColor is consumed by ContentGaps — kept in the orchestrator and passed down.
  const intentColor = (intent?: string) => {
    switch (intent) {
      case 'commercial': return 'text-accent-info bg-blue-500/10 border-blue-500/20';
      case 'informational': return 'text-accent-success bg-emerald-500/10 border-emerald-500/20';
      case 'transactional': return 'text-accent-warning bg-amber-500/10 border-amber-500/20';
      case 'navigational': return 'text-accent-cyan bg-cyan-500/10 border-cyan-500/20';
      default: return 'text-[var(--brand-text)] bg-zinc-500/10 border-zinc-500/20'; // raw-zinc-ok
    }
  };

  if (loading) {
    return <LoadingState message="Loading keyword strategy..." />;
  }

  if (strategyFetchError) {
    return (
      <ErrorState
        type="general"
        title="Failed to load keyword strategy"
        message="There was a problem loading your keyword strategy. Please try again."
        action={{ label: 'Retry', onClick: () => void refetchStrategy() }}
      />
    );
  }

  if (!workspaceId) {
    return (
      <div className="text-center py-16 text-[var(--brand-text-muted)] t-body">
        No workspace selected. Link a workspace to generate a keyword strategy.
      </div>
    );
  }

  // Header subtitle: in the decision-bands layout, lead with a decision summary when there is one;
  // otherwise (and always in the legacy layout) show artifact freshness — byte-identical to today.
  const summaryLine = buildStrategySummaryLine({
    contentGaps: strategy?.contentGaps?.length ?? 0,
    requested: metrics.requestedFeedback.length,
    quickWins: strategy?.quickWins?.length ?? 0,
  });
  const headerSubtitle = !isRealStrategy
    ? 'AI-powered keyword mapping for your entire site'
    : decisionBandsEnabled && summaryLine
      ? summaryLine
      : `Generated ${formatDate(strategy?.generatedAt)} · ${strategy?.pageMap?.length ?? 0} pages mapped`;

  // ── Shared elements (defined once; the two layouts arrange the same elements differently) ──
  const headerActions = (
    <StrategyHeaderActions
      isRealStrategy={isRealStrategy}
      generating={generation.generating}
      localSyncApplies={!!localSync?.applies}
      localNeedsRefresh={!!localSync?.localNeedsRefresh}
      refreshPending={generation.refresh.isPending}
      onIncremental={() => generation.generateStrategy('incremental')}
      onFullRefresh={() => generation.refresh.mutate({
        thenRegenerateStrategy: true,
        strategyGeneration: settings.buildStrategyGenerationParams(),
      })}
      onGenerate={() => generation.generateStrategy('full')}
    />
  );

  const headerEl = (
    <PageHeader
      title="Keyword Strategy"
      subtitle={headerSubtitle}
      icon={<Icon as={Target} size="lg" className="text-accent-brand" />}
      actions={headerActions}
    />
  );

  const refreshPromptEl = localSync?.applies && localSync.localNeedsRefresh ? (
    <RefreshOrderingPrompt
      open={generation.refreshOrderingPromptOpen}
      reason={localSync.localNeedsRefreshReason ?? 'stale'}
      lastLocalRefreshAt={localSync.lastLocalRefreshAt}
      onFullRefresh={() => {
        generation.refresh.mutate({
          thenRegenerateStrategy: true,
          strategyGeneration: settings.buildStrategyGenerationParams(),
        });
        generation.setRefreshOrderingPromptOpen(false);
      }}
      onGenerateAnyway={() => {
        generation.setRefreshOrderingPromptOpen(false);
        void generation.runStartJob('full');
      }}
      onCancel={() => generation.setRefreshOrderingPromptOpen(false)}
    />
  ) : null;

  const aiContextEl = !isRealStrategy && !generation.generating
    ? <AIContextIndicator workspaceId={workspaceId} feature="strategy" />
    : null;

  const localSeoEl = (
    <LocalSeoVisibilityPanel
      workspaceId={workspaceId}
      mode="strategy"
      onOpenKeywords={() => navigate(adminPath(workspaceId, 'seo-keywords'))}
    />
  );

  const feedbackNudgeEl = metrics.feedbackNewerThanStrategy ? (
    <StrategyFeedbackNudge
      requestedCount={metrics.requestedFeedback.length}
      declinedCount={metrics.declinedFeedback.length}
    />
  ) : null;

  const settingsEl = (
    <StrategySettings
      workspaceId={workspaceId}
      isAuxLoading={isAuxLoading}
      settingsOpen={settings.settingsOpen}
      setSettingsOpen={settings.setSettingsOpen}
      seoDataAvailable={settings.seoDataAvailable}
      seoDataMode={settings.seoDataMode}
      setSeoDataMode={settings.setSeoDataMode}
      maxPages={settings.maxPages}
      setMaxPages={settings.setMaxPages}
      competitors={settings.competitors}
      setCompetitors={settings.setCompetitors}
      businessContext={settings.businessContext}
      setBusinessContext={settings.setBusinessContext}
      contextOpen={settings.contextOpen}
      setContextOpen={settings.setContextOpen}
      discoveringCompetitors={settings.discoveringCompetitors}
      discoverError={settings.discoverError}
      onDiscoverCompetitors={settings.discoverCompetitors}
    />
  );

  const intelligenceSignalsEl = <IntelligenceSignals workspaceId={workspaceId} />;

  const progressEl = (
    <ProgressIndicator
      status={generation.generating ? 'running' : 'idle'}
      step={generation.activeStrategyJob?.message || (generation.startingStrategyJob ? 'Starting keyword strategy job...' : undefined)}
      percent={generation.activeStrategyJob?.total ? Math.round(((generation.activeStrategyJob.progress ?? 0) / generation.activeStrategyJob.total) * 100) : undefined}
    />
  );

  const errorEl = generation.error ? (
    <ErrorState
      type="general"
      title="Strategy Generation Failed"
      message={generation.error}
      action={{ label: 'Try Again', onClick: () => generation.generateStrategy('full') }}
    />
  ) : null;

  const nextStepsEl = generation.showNextSteps && isRealStrategy && !generation.generating ? (
    <NextStepsCard
      title="Strategy ready"
      variant="success"
      onDismiss={() => generation.setShowNextSteps(false)}
      staggerIndex={0}
      steps={[
        {
          label: 'Review Quick Wins',
          onClick: () => { generation.setShowNextSteps(false); setTimeout(() => document.getElementById('quick-wins-section')?.scrollIntoView({ behavior: 'smooth' }), 150); },
          estimatedTime: '2 min',
        },
      ]}
    />
  ) : null;

  const emptyStateEl = !isRealStrategy && !generation.generating ? <StrategyEmptyState /> : null;

  // Client keyword feedback: the legacy layout shows the combined card; the bands layout hoists
  // the requested-keyword triage into the Decide band and shows the declined log (only) in Reference.
  const clientFeedbackCombinedEl = (
    <ClientKeywordFeedback
      rows={feedback.rows}
      requested={metrics.requestedFeedback}
      declined={metrics.declinedFeedback}
      approved={metrics.approvedFeedback}
      addPending={feedback.addPending}
      addError={feedback.addError}
      onAdd={feedback.addRequestedKeyword}
      onDismissError={() => feedback.setAddError(null)}
    />
  );
  const clientFeedbackDeclinedEl = (
    <ClientKeywordFeedback
      rows={feedback.rows}
      requested={metrics.requestedFeedback}
      declined={metrics.declinedFeedback}
      approved={metrics.approvedFeedback}
      addPending={feedback.addPending}
      addError={feedback.addError}
      onAdd={feedback.addRequestedKeyword}
      onDismissError={() => feedback.setAddError(null)}
      showRequested={false}
    />
  );
  const requestedTriageEl = (
    <RequestedKeywordTriage
      requested={metrics.requestedFeedback}
      addPending={feedback.addPending}
      addError={feedback.addError}
      onAdd={feedback.addRequestedKeyword}
      onDismissError={() => feedback.setAddError(null)}
    />
  );

  // Real-strategy leaf elements — identical in both layouts; only the grouping/order differs.
  const realLeaves = isRealStrategy && strategy ? {
    stalenessNudges: (
      <StrategyStalenessNudges
        hasVolumeValidation={metrics.hasVolumeValidation}
        localSyncApplies={!!localSync?.applies}
        strategyStaleVsLocal={!!localSync?.strategyStaleVsLocal}
        lastLocalRefreshAt={localSync?.lastLocalRefreshAt}
        lastStrategyGeneratedAt={localSync?.lastStrategyGeneratedAt}
        dismissedRefreshAt={generation.dismissedRefreshAt}
        onDismiss={() => generation.setDismissedRefreshAt(localSync?.lastLocalRefreshAt ?? null)}
        onGenerate={() => generation.generateStrategy('full')}
      />
    ),
    statGrid: (
      <StrategyStatGrid
        filteredPageMap={metrics.filteredPageMap}
        totalPageCount={strategy.pageMap?.length ?? 0}
        totalImpressions={metrics.totalImpressions}
        totalClicks={metrics.totalClicks}
        ranked={metrics.ranked}
        avgPos={metrics.avgPos}
      />
    ),
    distribution: (
      <RankingDistribution
        filteredPageMap={metrics.filteredPageMap}
        ranked={metrics.ranked}
        top3={metrics.top3}
        top10={metrics.top10}
        top20={metrics.top20}
        beyond20={metrics.beyond20}
        notRankingCount={metrics.notRankingCount}
        intentCounts={metrics.intentCounts}
      />
    ),
    quickWins: (
      <div id="quick-wins-section">
        <QuickWins quickWins={strategy.quickWins ?? []} />
      </div>
    ),
    lhf: <LowHangingFruit pages={metrics.lowHangingFruit} />,
    // Act band (decision-bands layout only): Quick Wins + Low-Hanging Fruit merged into one
    // actionable card, plus decay + lost-query recovery surfaces. Legacy layout keeps quickWins/lhf.
    opportunitiesList: <OpportunitiesList quickWins={strategy.quickWins ?? []} lowHangingFruit={metrics.lowHangingFruit} workspaceId={workspaceId} />,
    decayingPages: <DecayingPagesCard workspaceId={workspaceId} />,
    lostQueries: <LostQueryRecoveryCard workspaceId={workspaceId} />,
    contentGaps: <ContentGaps contentGaps={strategy.contentGaps || []} workspaceId={workspaceId} intentColor={intentColor} />,
    keywordGaps: (
      <KeywordGaps
        keywordGaps={strategy.keywordGaps || []}
        difficultyColor={kdColor}
        workspaceId={workspaceId}
        navigate={navigate}
      />
    ),
    topicClusters: strategy.topicClusters && strategy.topicClusters.length > 0
      ? <TopicClusters clusters={strategy.topicClusters} />
      : null,
    cannibalization: strategy.cannibalization && strategy.cannibalization.length > 0
      ? <CannibalizationAlert entries={strategy.cannibalization} />
      : null,
    // Act band (decision-bands layout only): actionable triage queue. Legacy keeps cannibalization above.
    cannibalizationTriage: strategy.cannibalization && strategy.cannibalization.length > 0
      ? <CannibalizationTriage entries={strategy.cannibalization} workspaceId={workspaceId} />
      : null,
    strategyDiff: <StrategyDiff workspaceId={workspaceId} />,
    backlink: <BacklinkProfile workspaceId={workspaceId} />,
    competitive: (
      <CompetitiveIntel
        workspaceId={workspaceId}
        competitors={settings.competitors.split(/[,\n]+/).map(c => c.trim()).filter(Boolean)}
        seoDataAvailable={settings.seoDataAvailable}
        cachedKeywordGaps={strategy?.keywordGaps}
      />
    ),
    siteKeywords: (
      <SiteTargetKeywords
        workspaceId={workspaceId}
        siteKeywords={strategy.siteKeywords}
        siteKeywordMetrics={strategy.siteKeywordMetrics}
        trackedKeywords={tracking.trackedKeywords}
        trackingPending={tracking.trackingPending}
        trackingErrors={tracking.trackingErrors}
        onTrack={tracking.trackKeyword}
      />
    ),
    opportunities: <KeywordOpportunities opportunities={strategy.opportunities} />,
    howItWorks: <StrategyHowItWorks displayedSeoDataMode={displayedSeoDataMode} hasAnyRanking={metrics.hasAnyRanking} />,
  } : null;

  // ── Decision-bands layout (flag ON) ──
  const bandsAnalysis = (
    <div className="space-y-8">
      {headerEl}
      {refreshPromptEl}
      {aiContextEl}
      {localSeoEl}
      <StrategyBand label="Decide" first>
        <DecisionQueue workspaceId={workspaceId} />
        {feedbackNudgeEl}
        {metrics.requestedFeedback.length > 0 && requestedTriageEl}
        {settingsEl}
      </StrategyBand>
      {progressEl}
      {errorEl}
      {nextStepsEl}
      {emptyStateEl}
      {realLeaves && (
        <>
          {realLeaves.stalenessNudges}
          <StrategyBand label="Act">
            {realLeaves.contentGaps}
            {realLeaves.opportunitiesList}
            {realLeaves.decayingPages}
            {realLeaves.lostQueries}
            {realLeaves.keywordGaps}
            {realLeaves.cannibalizationTriage}
            {realLeaves.strategyDiff}
          </StrategyBand>
          <StrategyBand label="Reference">
            {realLeaves.statGrid}
            {realLeaves.distribution}
            {realLeaves.topicClusters}
            {realLeaves.backlink}
            {realLeaves.competitive}
            {realLeaves.siteKeywords}
            {realLeaves.opportunities}
            {clientFeedbackDeclinedEl}
            {intelligenceSignalsEl}
            {realLeaves.howItWorks}
          </StrategyBand>
        </>
      )}
    </div>
  );

  // ── Legacy sequential layout (flag OFF) — byte-identical to pre-flag ──
  const legacyAnalysis = (
    <div className="space-y-8">
      {headerEl}
      {refreshPromptEl}
      {aiContextEl}
      {localSeoEl}
      {feedbackNudgeEl}
      {clientFeedbackCombinedEl}
      {settingsEl}
      {intelligenceSignalsEl}
      {progressEl}
      {errorEl}
      {nextStepsEl}
      {emptyStateEl}
      {realLeaves && (
        <>
          {realLeaves.stalenessNudges}
          {realLeaves.statGrid}
          {realLeaves.distribution}
          {realLeaves.quickWins}
          {realLeaves.lhf}
          {realLeaves.contentGaps}
          {realLeaves.keywordGaps}
          {/* ── Reference & Analysis ── */}
          <div className="border-t border-[var(--brand-border)] my-6 flex items-center gap-3">
            <span className="t-caption text-[var(--brand-text-muted)] uppercase tracking-wide">Reference & Analysis</span>
            <div className="flex-1 border-t border-[var(--brand-border)]" />
          </div>
          {realLeaves.topicClusters}
          {realLeaves.cannibalization}
          {realLeaves.strategyDiff}
          {realLeaves.backlink}
          {realLeaves.competitive}
          {realLeaves.siteKeywords}
          {realLeaves.opportunities}
          {realLeaves.howItWorks}
        </>
      )}
    </div>
  );

  return (
    <div className="space-y-8">
      {/* tab-deeplink-ok: KeywordStrategy is not a direct navigation target for ?tab= */}
      <TabBar
        tabs={[{ id: 'analysis', label: 'Analysis' }, { id: 'guide', label: 'Guide' }]}
        active={strategyTab}
        onChange={(id) => setStrategyTab(id as 'analysis' | 'guide')}
      />
      {strategyTab === 'guide' && <KeywordStrategyGuide />}
      {strategyTab === 'analysis' && (decisionBandsEnabled ? bandsAnalysis : legacyAnalysis)}
    </div>
  );
}
