import { useState, useEffect } from 'react';
import type { MetricsSource } from '../../shared/types/keywords.js';
import {
  Loader2, Target, ChevronDown, ChevronRight, RefreshCw,
  Sparkles, Briefcase,
  BarChart3, Users, Search, FileText,
  Eye, MousePointerClick, Trophy, AlertTriangle, Plus, Check, Send,
} from 'lucide-react';
import { StatCard, SectionCard, AIContextIndicator, TabBar, ErrorState, ProgressIndicator, NextStepsCard, LoadingState, Icon } from './ui';
import { KeywordStrategyGuide } from './strategy/KeywordStrategyGuide';
import { useKeywordStrategy } from '../hooks/admin';
import { useQueryClient } from '@tanstack/react-query';
import { BacklinkProfile } from './strategy/BacklinkProfile';
import { CompetitiveIntel } from './strategy/CompetitiveIntel';
import { ContentGaps } from './strategy/ContentGaps';
import { QuickWins } from './strategy/QuickWins';
import { KeywordGaps } from './strategy/KeywordGaps';
import { LowHangingFruit } from './strategy/LowHangingFruit';
import { TopicClusters } from './strategy/TopicClusters';
import { CannibalizationAlert } from './strategy/CannibalizationAlert';
import { StrategyDiff } from './strategy/StrategyDiff';
import { IntelligenceSignals } from './strategy/IntelligenceSignals';
import { keywords, rankTracking } from '../api/seo';
import { workspaces } from '../api';
import { clientActions } from '../api/clientActions';
import { queryKeys } from '../lib/queryKeys';
import { useBackgroundTasks } from '../hooks/useBackgroundTasks';
import { BACKGROUND_JOB_TYPES } from '../../shared/types/background-jobs';

/** Minimum monthly search volume to display a strategy card. Cards below this are noise. */
const VOLUME_THRESHOLD = 10;

interface PageKeywordMap {
  pagePath: string;
  pageTitle: string;
  primaryKeyword: string;
  secondaryKeywords: string[];
  searchIntent?: string;
  currentPosition?: number;
  impressions?: number;
  clicks?: number;
  volume?: number;
  difficulty?: number;
  cpc?: number;
  metricsSource?: MetricsSource;
  validated?: boolean;
  secondaryMetrics?: { keyword: string; volume: number; difficulty: number }[];
}

interface Props {
  workspaceId: string;
  siteId?: string;
}

export function KeywordStrategyPanel({ workspaceId }: Props) {
  const queryClient = useQueryClient();
  const { jobs, startJob, findActiveJob } = useBackgroundTasks();
  const [startingStrategyJob, setStartingStrategyJob] = useState(false);
  const [lastStartedJobId, setLastStartedJobId] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  // React Query hook replaces manual data fetching
  const { data: keywordData, isLoading: loading } = useKeywordStrategy(workspaceId);
  const strategy = keywordData?.strategy || null;
  // A "real" strategy has been generated by the AI pipeline (non-null generatedAt).
  // The server may synthesize a shell { pageMap, generatedAt: null, siteKeywords: [], opportunities: [] }
  // when page_keywords rows exist but no strategy blob — that case must render as "no strategy yet"
  // in this component, while still exposing pageMap via Page Intelligence separately.
  const isRealStrategy = strategy?.generatedAt != null;
  const seoDataAvailableFromHook = keywordData?.seoDataAvailable || false;
  const [businessContext, setBusinessContext] = useState('');
  const [contextOpen, setContextOpen] = useState(false);
  const [seoDataAvailable, setSeoDataAvailable] = useState(seoDataAvailableFromHook);
  const [seoDataMode, setSeoDataMode] = useState<'none' | 'quick' | 'full'>('none');
  const [maxPages, setMaxPages] = useState<number>(500);
  const [competitors, setCompetitors] = useState('');
  const [discoveringCompetitors, setDiscoveringCompetitors] = useState(false);
  const [discoverError, setDiscoverError] = useState<string | null>(null);
  const [settingsOpen, setSettingsOpen] = useState(true);
  const [showNextSteps, setShowNextSteps] = useState(false);
  const [trackedKeywords, setTrackedKeywords] = useState<Set<string>>(new Set());
  const [providerList, setProviderList] = useState<{ name: string; configured: boolean }[]>([]);
  const [activeProvider, setActiveProvider] = useState<string | undefined>(undefined);
  const [strategyTab, setStrategyTab] = useState<'analysis' | 'guide'>('analysis');
  const [sendingToClient, setSendingToClient] = useState(false);
  const [sentToClient, setSentToClient] = useState(false);
  const activeStrategyJob = findActiveJob({ type: BACKGROUND_JOB_TYPES.KEYWORD_STRATEGY, workspaceId });
  const completedStartedJob = lastStartedJobId ? jobs.find(job => job.id === lastStartedJobId) : undefined;
  const generating = startingStrategyJob || Boolean(activeStrategyJob);
  const displayedSeoDataMode = strategy?.seoDataMode ?? strategy?.semrushMode;

  // Seed trackedKeywords from server on mount so buttons reflect actual state
  useEffect(() => {
    rankTracking.keywords(workspaceId)
      .then(kws => setTrackedKeywords(new Set((kws || []).map(k => k.query))))
      .catch(() => {});
  }, [workspaceId]);

  // Load provider status + workspace preference
  useEffect(() => {
    keywords.providerStatus()
      .then(data => { if (data?.providers) setProviderList(data.providers); })
      .catch(() => {});
    workspaces.getById(workspaceId)
      .then((ws) => {
        const wsObj = ws as Record<string, unknown> | null;
        if (wsObj?.seoDataProvider) setActiveProvider(wsObj.seoDataProvider as string);
      })
      .catch(() => {});
  }, [workspaceId]);

  // Initialize SEO provider availability from React Query hook
  useEffect(() => {
    setSeoDataAvailable(seoDataAvailableFromHook);
    if (seoDataAvailableFromHook) {
      // Default to quick mode when an SEO data provider is available
      setSeoDataMode(prev => prev === 'none' ? 'quick' : prev);
    } else {
      setSeoDataMode('none');
    }
  }, [seoDataAvailableFromHook]);

  // Load saved competitor domains from React Query hook data
  useEffect(() => {
    if (keywordData?.workspaceData?.competitorDomains?.length && !competitors) {
      setCompetitors(keywordData.workspaceData.competitorDomains.join(', '));
    }
  }, [keywordData?.workspaceData?.competitorDomains, competitors]);

  // Sync business context + competitors from loaded strategy
  useEffect(() => {
    if (strategy?.businessContext && !businessContext) {
      setBusinessContext(strategy.businessContext);
    }
    const savedSeoDataMode = strategy?.seoDataMode ?? strategy?.semrushMode;
    if (savedSeoDataMode && savedSeoDataMode !== 'none') {
      setSeoDataMode(savedSeoDataMode);
    }
  }, [strategy]);

  // effect-layout-ok: active background jobs can predate this component mount.
  useEffect(() => {
    if (activeStrategyJob && !lastStartedJobId) {
      setLastStartedJobId(activeStrategyJob.id);
    }
  }, [activeStrategyJob, lastStartedJobId]);

  // effect-layout-ok: background job completion arrives asynchronously via WebSocket/job state.
  useEffect(() => {
    if (!completedStartedJob) return;
    if (completedStartedJob.status === 'done') {
      queryClient.invalidateQueries({ queryKey: queryKeys.admin.keywordStrategy(workspaceId) });
      setShowNextSteps(true);
      setLastStartedJobId(null);
    } else if (completedStartedJob.status === 'error') {
      setError(completedStartedJob.error || completedStartedJob.message || 'Failed to generate strategy');
      setLastStartedJobId(null);
    } else if (completedStartedJob.status === 'cancelled') {
      setError('Strategy generation was cancelled');
      setLastStartedJobId(null);
    }
  }, [completedStartedJob, queryClient, workspaceId]);

  const generateStrategy = async (strategyMode: 'full' | 'incremental' = 'full') => {
    if (generating) return;
    setStartingStrategyJob(true);
    setShowNextSteps(false);
    setError(null);
    try {
      const compList = competitors.trim() ? competitors.split(/[,\n]+/).map(s => s.trim()).filter(Boolean) : undefined;
      const jobId = await startJob(BACKGROUND_JOB_TYPES.KEYWORD_STRATEGY, {
        mode: strategyMode,
        workspaceId,
        businessContext: businessContext.trim() || undefined,
        seoDataMode: seoDataAvailable ? seoDataMode : 'none',
        competitorDomains: compList,
        maxPages: maxPages || undefined,
      });
      if (jobId) {
        setLastStartedJobId(jobId);
      } else {
        setError('Failed to start keyword strategy generation');
      }
    } catch (err) {
      console.error('KeywordStrategy operation failed:', err);
      setError('Failed to generate strategy');
    } finally {
      setStartingStrategyJob(false);
    }
  };

  const trackKeyword = async (kw: string) => {
    if (trackedKeywords.has(kw)) return;
    try {
      await rankTracking.addKeyword(workspaceId, { query: kw });
      setTrackedKeywords(prev => new Set(prev).add(kw));
    } catch {
      // silently ignore duplicates — server deduplicates
    }
  };

  const positionColor = (pos?: number) => {
    if (!pos) return 'text-[var(--brand-text-muted)]';
    if (pos <= 3) return 'text-accent-success';
    if (pos <= 10) return 'text-accent-brand';
    if (pos <= 20) return 'text-accent-warning';
    return 'text-accent-danger';
  };

  const difficultyColor = (kd?: number) => {
    if (kd === undefined) return 'text-[var(--brand-text-muted)]';
    if (kd <= 30) return 'text-accent-success';
    if (kd <= 50) return 'text-accent-warning';
    if (kd <= 70) return 'text-accent-orange';
    return 'text-accent-danger';
  };

  const intentColor = (intent?: string) => {
    switch (intent) {
      case 'commercial': return 'text-accent-info bg-blue-500/10 border-blue-500/20';
      case 'informational': return 'text-accent-success bg-emerald-500/10 border-emerald-500/20';
      case 'transactional': return 'text-accent-warning bg-amber-500/10 border-amber-500/20';
      case 'navigational': return 'text-accent-cyan bg-cyan-500/10 border-cyan-500/20';
      default: return 'text-[var(--brand-text)] bg-zinc-500/10 border-zinc-500/20'; // raw-zinc-ok
    }
  };

  // Computed metrics
  const pageMap: PageKeywordMap[] = strategy?.pageMap || [];
  // Filter out pages with known-low search volume to reduce noise in rendered cards.
  // Pages without volume data (undefined) are kept — they haven't been enriched yet.
  const filteredPageMap = pageMap.filter(
    (p: PageKeywordMap) => (p.volume ?? VOLUME_THRESHOLD) >= VOLUME_THRESHOLD
  );
  const ranked = filteredPageMap.filter((p: PageKeywordMap) => p.currentPosition);
  const avgPos = ranked.length > 0 ? ranked.reduce((s: number, p: PageKeywordMap) => s + (p.currentPosition || 0), 0) / ranked.length : 0;
  const totalImpressions = filteredPageMap.reduce((s: number, p: PageKeywordMap) => s + (p.impressions || 0), 0);
  const totalClicks = filteredPageMap.reduce((s: number, p: PageKeywordMap) => s + (p.clicks || 0), 0);
  const top3 = ranked.filter((p: PageKeywordMap) => (p.currentPosition || 99) <= 3);
  const top10 = ranked.filter((p: PageKeywordMap) => (p.currentPosition || 99) <= 10 && (p.currentPosition || 0) > 3);
  const top20 = ranked.filter((p: PageKeywordMap) => (p.currentPosition || 99) <= 20 && (p.currentPosition || 0) > 10);
  const beyond20 = ranked.filter((p: PageKeywordMap) => (p.currentPosition || 0) > 20);
  const notRankingCount = filteredPageMap.length - ranked.length;

  const lowHangingFruit = ranked
    .filter((p: PageKeywordMap) => (p.currentPosition || 0) >= 4 && (p.currentPosition || 0) <= 20 && (p.impressions || 0) > 20)
    .sort((a: PageKeywordMap, b: PageKeywordMap) => (b.impressions || 0) - (a.impressions || 0))
    .slice(0, 6);

  const sendStrategyToClient = async () => {
    if (!strategy) return;
    setSendingToClient(true);
    setError(null);
    try {
      await clientActions.create(workspaceId, {
        sourceType: 'keyword_strategy',
        sourceId: `keyword-strategy:${strategy.generatedAt || new Date().toISOString()}`,
        title: 'Keyword strategy recommendations',
        summary: `Review the current keyword strategy: ${filteredPageMap.length} mapped page${filteredPageMap.length !== 1 ? 's' : ''}, ${lowHangingFruit.length} low-hanging opportunity${lowHangingFruit.length !== 1 ? 'ies' : 'y'}, and ${(strategy.contentGaps?.length ?? 0)} content gap${(strategy.contentGaps?.length ?? 0) !== 1 ? 's' : ''}.`,
        priority: lowHangingFruit.length > 0 || (strategy.contentGaps?.length ?? 0) > 0 ? 'high' : 'medium',
        payload: {
          generatedAt: strategy.generatedAt,
          mappedPages: filteredPageMap.map(p => ({
            page: p.pagePath,
            keyword: p.primaryKeyword,
            currentPosition: p.currentPosition,
          })),
          quickWins: strategy.quickWins ?? [],
          contentGaps: strategy.contentGaps ?? [],
          opportunities: strategy.opportunities ?? [],
          lowHangingFruit,
        },
      });
      setSentToClient(true);
    } catch (err) {
      console.error('KeywordStrategy operation failed:', err);
      setError('Failed to send keyword strategy to client');
    } finally {
      setSendingToClient(false);
    }
  };

  const intentCounts = filteredPageMap.reduce((acc: Record<string, number>, p: PageKeywordMap) => {
    const intent = p.searchIntent || 'unknown';
    acc[intent] = (acc[intent] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  if (loading) {
    return <LoadingState message="Loading keyword strategy..." />;
  }

  if (!workspaceId) {
    return (
      <div className="text-center py-16 text-[var(--brand-text-muted)] t-ui">
        No workspace selected. Link a workspace to generate a keyword strategy.
      </div>
    );
  }

  return (
    <div className="space-y-8">
      {/* tab-deeplink-ok: KeywordStrategy is not a direct navigation target for ?tab= */}
      <TabBar
        tabs={[{ id: 'analysis', label: 'Analysis' }, { id: 'guide', label: 'Guide' }]}
        active={strategyTab}
        onChange={(id) => setStrategyTab(id as 'analysis' | 'guide')}
      />
      {strategyTab === 'guide' && <KeywordStrategyGuide />}
      {strategyTab === 'analysis' && <div className="space-y-8">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="t-ui font-semibold text-[var(--brand-text-bright)]">Keyword Strategy</h3>
          <p className="t-caption-sm text-[var(--brand-text-muted)] mt-0.5">
            {isRealStrategy
              ? `Generated ${new Date(strategy.generatedAt).toLocaleDateString()} · ${strategy.pageMap?.length ?? 0} pages mapped`
              : 'AI-powered keyword mapping for your entire site'}
          </p>
        </div>
        <div className="flex items-center gap-2">
          {isRealStrategy && (
            <button
              onClick={() => generateStrategy('incremental')}
              disabled={generating}
              title="Re-analyzes only pages not updated in the last 7 days. Faster and lower cost than a full regeneration."
              className="px-3 py-1.5 rounded-[var(--radius-lg)] t-caption border border-[var(--brand-border)] text-[var(--brand-text)] hover:text-[var(--brand-text-bright)] hover:border-[var(--brand-border-hover)] transition-colors disabled:opacity-50"
            >
              Update changed pages
            </button>
          )}
          {isRealStrategy && (
            <button
              onClick={sendStrategyToClient}
              disabled={sendingToClient || sentToClient}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-[var(--radius-lg)] border border-[var(--brand-border)] text-[var(--brand-text)] hover:text-[var(--brand-text-bright)] hover:border-[var(--brand-border-hover)] transition-colors disabled:opacity-50 t-caption font-medium"
            >
              <Icon as={sentToClient ? Check : Send} size="sm" className={sentToClient ? 'text-emerald-400' : undefined} />
              {sendingToClient ? 'Sending...' : sentToClient ? 'Sent' : 'Send to Client'}
            </button>
          )}
          <button
            onClick={() => generateStrategy('full')}
            disabled={generating}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-[var(--radius-lg)] bg-teal-600 hover:bg-teal-500 disabled:opacity-50 text-white t-caption font-medium transition-colors"
          >
            {generating ? (
              <><Icon as={Loader2} size="sm" className="animate-spin" /> Generating...</>
            ) : isRealStrategy ? (
              <><Icon as={RefreshCw} size="sm" /> Regenerate</>
            ) : (
              <><Icon as={Sparkles} size="sm" /> Generate Strategy</>
            )}
          </button>
        </div>
      </div>

      {!isRealStrategy && !generating && (
        <AIContextIndicator workspaceId={workspaceId} feature="strategy" />
      )}

      {/* Settings Panel */}
      {/* pr-check-disable-next-line -- brand asymmetric signature on KeywordStrategy settings panel; intentional non-SectionCard chrome (collapsible, button-as-first-child) */}
      <div className="bg-[var(--surface-2)] border border-[var(--brand-border)] overflow-hidden rounded-[var(--radius-signature-lg)]">
        <button
          onClick={() => setSettingsOpen(!settingsOpen)}
          className="w-full flex items-center justify-between px-4 py-2.5 hover:bg-[var(--surface-3)]/20 transition-colors text-left"
        >
          <div className="flex items-center gap-2">
            <Icon as={Briefcase} size="md" className="text-accent-brand" />
            <span className="t-caption font-semibold text-[var(--brand-text-bright)]">Strategy Settings</span>
            {!settingsOpen && (
              <span className="t-caption-sm text-[var(--brand-text-muted)]">
                {seoDataMode !== 'none' ? `SEO data: ${seoDataMode}` : ''}
                {maxPages > 0 ? `${seoDataMode !== 'none' ? ' · ' : ''}${maxPages} pages max` : `${seoDataMode !== 'none' ? ' · ' : ''}All pages`}
                {businessContext ? ` · Context set` : ''}
                {competitors.trim() ? ` · ${competitors.split(/[,\n]+/).filter(Boolean).length} competitors` : ''}
              </span>
            )}
          </div>
          <Icon as={settingsOpen ? ChevronDown : ChevronRight} size="md" className="text-[var(--brand-text-muted)]" />
        </button>
        {settingsOpen && (
          <div className="px-4 pb-4 space-y-6">
            {/* SEO Data Provider */}
            {providerList.filter(p => p.configured).length > 1 && (
              <div>
                <div className="flex items-center gap-1.5 mb-2">
                  <Icon as={BarChart3} size="md" className="text-accent-brand" />
                  <span className="t-caption-sm text-[var(--brand-text)] font-semibold uppercase tracking-wider">SEO Data Provider</span>
                </div>
                <div className="grid grid-cols-2 gap-3">
                  {providerList.filter(p => p.configured).map(p => (
                    <button
                      key={p.name}
                      onClick={() => {
                        setActiveProvider(p.name);
                        workspaces.update(workspaceId, { seoDataProvider: p.name }).catch(() => {});
                      }}
                      className={`px-3 py-2 rounded-[var(--radius-lg)] border t-caption font-medium transition-all ${
                        (activeProvider || 'semrush') === p.name
                          ? 'border-teal-500/50 bg-teal-500/10 text-accent-brand'
                          : 'border-[var(--brand-border-hover)] bg-[var(--surface-3)] text-[var(--brand-text-muted)] hover:text-[var(--brand-text-bright)]'
                      }`}
                    >
                      <div className="font-semibold capitalize">{p.name === 'dataforseo' ? 'DataForSEO' : 'SEMRush'}</div>
                      <div className="t-caption-sm mt-0.5 opacity-70">
                        {p.name === 'dataforseo' ? 'Pay-as-you-go' : 'Subscription'}
                      </div>
                    </button>
                  ))}
                </div>
                <p className="t-caption-sm text-[var(--brand-text-muted)] mt-1.5">
                  {(activeProvider || 'semrush') === 'dataforseo'
                    ? 'DataForSEO: pay-per-call pricing (~$0.01-0.08/call). Uses same cache layer.'
                    : 'SEMRush: subscription-based traditional keyword intelligence provider.'}
                </p>
              </div>
            )}

            {/* SEO Data Mode */}
            {seoDataAvailable && (
              <div>
                <div className="flex items-center gap-1.5 mb-2">
                  <Icon as={BarChart3} size="md" className="text-accent-orange" />
                  <span className="t-caption-sm text-[var(--brand-text)] font-semibold uppercase tracking-wider">SEO Data Mode</span>
                </div>
                <div className="grid grid-cols-3 gap-3">
                  {(['none', 'quick', 'full'] as const).map(mode => (
                    <button
                      key={mode}
                      onClick={() => setSeoDataMode(mode)}
                      className={`px-3 py-2 rounded-[var(--radius-lg)] border t-caption font-medium transition-all ${
                        seoDataMode === mode
                          ? 'border-orange-500/50 bg-orange-500/10 text-accent-orange'
                          : 'border-[var(--brand-border-hover)] bg-[var(--surface-3)] text-[var(--brand-text-muted)] hover:text-[var(--brand-text-bright)]'
                      }`}
                    >
                      <div className="font-semibold capitalize">{mode === 'none' ? 'Off' : mode}</div>
                      <div className="t-caption-sm mt-0.5 opacity-70">
                        {mode === 'none' && 'AI + GSC only'}
                        {mode === 'quick' && '~500 credits'}
                        {mode === 'full' && '~7,500 credits'}
                      </div>
                    </button>
                  ))}
                </div>
                <p className="t-caption-sm text-[var(--brand-text-muted)] mt-1.5">
                  {seoDataMode === 'quick' && 'Enriches keywords with real search volume + difficulty scores from your configured SEO provider.'}
                  {seoDataMode === 'full' && 'Full competitive analysis: domain keywords, competitor gaps, related keywords, volume + difficulty.'}
                  {seoDataMode === 'none' && 'Uses AI + Google Search Console data only. No SEO provider credits used.'}
                </p>
              </div>
            )}

            {/* Competitor Domains */}
            {seoDataAvailable && (
              <div>
                <div className="flex items-center justify-between mb-1">
                  <div className="flex items-center gap-1.5">
                    <Icon as={Users} size="md" className="text-accent-orange" />
                    <span className="t-caption-sm text-[var(--brand-text)] font-semibold uppercase tracking-wider">Competitor Domains</span>
                  </div>
                  <button
                    onClick={async () => {
                      setDiscoveringCompetitors(true);
                      setDiscoverError(null);
                      try {
                        const result = await keywords.discoverCompetitors(workspaceId);
                        if (result?.competitors?.length) {
                          const domains = result.competitors.slice(0, 5).map(c => c.domain);
                          setCompetitors(domains.join(', '));
                          await keywords.saveCompetitors(workspaceId, domains);
                        } else {
                          setDiscoverError('No organic competitors were found for this domain.');
                        }
                      } catch (err: any) {
                        setDiscoverError(err?.message || 'Failed to discover competitors. Check that your domain is set and an SEO provider is configured.');
                      } finally {
                        setDiscoveringCompetitors(false);
                      }
                    }}
                    disabled={discoveringCompetitors}
                    className="flex items-center gap-1 px-2 py-0.5 rounded bg-orange-500/10 border border-orange-500/20 t-micro text-accent-orange font-medium hover:bg-orange-500/20 transition-all disabled:opacity-50"
                  >
                    {discoveringCompetitors ? <Icon as={Loader2} size="sm" className="animate-spin" /> : <Icon as={Search} size="sm" className="text-accent-orange" />}
                    {discoveringCompetitors ? 'Discovering...' : 'Auto-Discover'}
                  </button>
                </div>
                <input
                  type="text"
                  value={competitors}
                  onChange={e => setCompetitors(e.target.value)}
                  placeholder="e.g. competitor1.com, competitor2.com"
                  className="w-full px-3 py-2 bg-[var(--surface-3)] border border-[var(--brand-border-hover)] rounded-[var(--radius-lg)] t-caption text-[var(--brand-text-bright)] placeholder:text-[var(--brand-text-muted)] focus:outline-none focus:border-orange-500"
                />
                <p className="t-caption-sm text-[var(--brand-text-muted)] mt-1">Comma-separated (max 5). Auto-discover uses your configured SEO data provider to find organic competitors. These persist between strategy runs.</p>
                {discoverError && <p className="t-caption-sm text-accent-danger mt-1">{discoverError}</p>}
              </div>
            )}

            {/* Page Limit */}
            <div>
              <div className="flex items-center gap-1.5 mb-2">
                <Icon as={FileText} size="md" className="text-accent-brand" />
                <span className="t-caption-sm text-[var(--brand-text)] font-semibold uppercase tracking-wider">Page Limit</span>
              </div>
              <div className="grid grid-cols-4 gap-3">
                {([200, 500, 1000, 0] as const).map(cap => (
                  <button
                    key={cap}
                    onClick={() => setMaxPages(cap)}
                    className={`px-3 py-2 rounded-[var(--radius-lg)] border t-caption font-medium transition-all ${
                      maxPages === cap
                        ? 'border-teal-500/50 bg-teal-500/10 text-accent-brand'
                        : 'border-[var(--brand-border-hover)] bg-[var(--surface-3)] text-[var(--brand-text-muted)] hover:text-[var(--brand-text-bright)]'
                    }`}
                  >
                    <div className="font-semibold">{cap === 0 ? 'All' : cap}</div>
                    <div className="t-caption-sm mt-0.5 opacity-70">
                      {cap === 200 && '~2-3 min'}
                      {cap === 500 && '~5-7 min'}
                      {cap === 1000 && '~10-15 min'}
                      {cap === 0 && 'No limit'}
                    </div>
                  </button>
                ))}
              </div>
              <p className="t-caption-sm text-[var(--brand-text-muted)] mt-1.5">
                {maxPages === 0
                  ? 'Processes every page on the site. May be slow for 500+ page sites.'
                  : `Prioritizes the top ${maxPages} pages by importance (homepage, key service pages, pages with metadata). Skips utility pages.`}
              </p>
            </div>

            {/* Business Context */}
            <div>
              <button
                onClick={() => setContextOpen(!contextOpen)}
                className="flex items-center gap-1.5 mb-1"
              >
                <Icon as={Briefcase} size="md" className="text-accent-brand" />
                <span className="t-caption-sm text-[var(--brand-text)] font-semibold uppercase tracking-wider">Business Context</span>
                <Icon as={contextOpen ? ChevronDown : ChevronRight} size="sm" className="text-[var(--brand-text-muted)]" />
              </button>
              {contextOpen && (
                <div className="space-y-1.5">
                  <textarea
                    value={businessContext}
                    onChange={e => setBusinessContext(e.target.value)}
                    placeholder={`Example: We are a dental practice in Austin, TX. We offer general, cosmetic, and pediatric dentistry. Target audience: families 25-55. Competitors: Aspen Dental, local practices.`}
                    rows={3}
                    className="w-full px-3 py-2 bg-[var(--surface-3)] border border-[var(--brand-border-hover)] rounded-[var(--radius-lg)] t-caption text-[var(--brand-text-bright)] placeholder:text-[var(--brand-text-muted)] focus:outline-none focus:border-teal-500 resize-y"
                  />
                  <p className="t-caption-sm text-[var(--brand-text-muted)]">Saved with your strategy. Include: locations, services, audience, differentiators.</p>
                </div>
              )}
            </div>
          </div>
        )}
      </div>

      <IntelligenceSignals workspaceId={workspaceId} />

      {/* Progress Indicator */}
      <ProgressIndicator
        status={generating ? 'running' : 'idle'}
        step={activeStrategyJob?.message || (startingStrategyJob ? 'Starting keyword strategy job...' : undefined)}
        percent={activeStrategyJob?.total ? Math.round(((activeStrategyJob.progress ?? 0) / activeStrategyJob.total) * 100) : undefined}
      />

      {error && (
        <ErrorState
          type="general"
          title="Strategy Generation Failed"
          message={error}
          action={{ label: 'Try Again', onClick: () => generateStrategy('full') }}
        />
      )}

      {showNextSteps && isRealStrategy && !generating && (
        <NextStepsCard
          title="Strategy ready"
          variant="success"
          onDismiss={() => setShowNextSteps(false)}
          staggerIndex={0}
          steps={[
            {
              label: 'Review Quick Wins',
              onClick: () => { setShowNextSteps(false); setTimeout(() => document.getElementById('quick-wins-section')?.scrollIntoView({ behavior: 'smooth' }), 150); },
              estimatedTime: '2 min',
            },
          ]}
        />
      )}

      {!isRealStrategy && !generating && (
        <SectionCard noPadding>
          <div className="px-6 py-12 text-center">
            <Icon as={Target} size="2xl" className="text-[var(--brand-text-muted)] mx-auto mb-3" />
            <p className="t-ui text-[var(--brand-text)] mb-1">No keyword strategy yet</p>
            <p className="t-caption-sm text-[var(--brand-text-muted)] max-w-md mx-auto">
              Generate an AI-powered keyword strategy based on your site's pages and Google Search Console data.
              This will map target keywords to each page and guide all future AI rewrites.
            </p>
          </div>
        </SectionCard>
      )}

      {isRealStrategy && strategy && (
        <>
          {/* ── Unvalidated Strategy Warning ── */}
          {!(strategy.pageMap ?? []).some((p: PageKeywordMap) => p.volume && p.volume > 0) && (
            <div className="bg-amber-500/10 border border-amber-500/30 rounded-[var(--radius-lg)] px-4 py-3 flex items-start gap-2.5">
              <Icon as={AlertTriangle} size="md" className="text-accent-warning flex-shrink-0 mt-0.5" />
              <div className="t-caption text-accent-warning leading-relaxed">
                <strong className="text-accent-warning">This strategy was generated without keyword volume validation.</strong>{' '}
                Keywords, volume, and difficulty data may not reflect real search demand. Enable an SEO data provider for validated keyword recommendations.
              </div>
            </div>
          )}

          {/* ── Summary Dashboard ── */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            <StatCard size="hero" label="Pages Mapped" value={filteredPageMap.length} sub={filteredPageMap.length < (strategy.pageMap?.length ?? 0) ? `${(strategy.pageMap?.length ?? 0) - filteredPageMap.length} below threshold` : undefined} />
            <StatCard size="hero" label="Impressions" value={totalImpressions.toLocaleString()} icon={Eye} sub="last 90 days" />
            <StatCard size="hero" label="Clicks" value={totalClicks.toLocaleString()} icon={MousePointerClick} sub={totalImpressions > 0 ? `${((totalClicks / totalImpressions) * 100).toFixed(1)}% CTR` : undefined} />
            <StatCard size="hero" label="Avg Position" value={ranked.length > 0 ? `#${avgPos.toFixed(1)}` : '—'} icon={Trophy} valueColor={positionColor(avgPos)} sub={`${ranked.length} pages ranking`} />
          </div>

          {/* ── Performance Tiers Bar ── */}
          {ranked.length > 0 && (
            <SectionCard
              title="Ranking Distribution"
              titleExtra={<span className="t-caption-sm text-[var(--brand-text-muted)] ml-2">{ranked.length} of {filteredPageMap.length} pages with ranking data</span>}
            >
              <div className="flex h-4 rounded-[var(--radius-pill)] overflow-hidden bg-[var(--surface-3)]">
                {top3.length > 0 && <div className="bg-emerald-500 h-full transition-all" style={{ width: `${(top3.length / filteredPageMap.length) * 100}%` }} />}
                {top10.length > 0 && <div className="bg-teal-500 h-full transition-all" style={{ width: `${(top10.length / filteredPageMap.length) * 100}%` }} />}
                {top20.length > 0 && <div className="bg-amber-500 h-full transition-all" style={{ width: `${(top20.length / filteredPageMap.length) * 100}%` }} />}
                {beyond20.length > 0 && <div className="bg-red-500/60 h-full transition-all" style={{ width: `${(beyond20.length / filteredPageMap.length) * 100}%` }} />}
                {notRankingCount > 0 && <div className="bg-[var(--surface-3)] h-full transition-all" style={{ width: `${(notRankingCount / filteredPageMap.length) * 100}%` }} />}
              </div>
              <div className="flex items-center gap-4 mt-2 flex-wrap">
                <span className="flex items-center gap-1.5 t-caption-sm"><span className="w-2.5 h-2.5 rounded-[var(--radius-pill)] bg-emerald-500 inline-block" /> <span className="text-accent-success font-medium">{top3.length}</span> <span className="text-[var(--brand-text-muted)]">Top 3</span></span>
                <span className="flex items-center gap-1.5 t-caption-sm"><span className="w-2.5 h-2.5 rounded-[var(--radius-pill)] bg-teal-500 inline-block" /> <span className="text-accent-brand font-medium">{top10.length}</span> <span className="text-[var(--brand-text-muted)]">4–10</span></span>
                <span className="flex items-center gap-1.5 t-caption-sm"><span className="w-2.5 h-2.5 rounded-[var(--radius-pill)] bg-amber-500 inline-block" /> <span className="text-accent-warning font-medium">{top20.length}</span> <span className="text-[var(--brand-text-muted)]">11–20</span></span>
                <span className="flex items-center gap-1.5 t-caption-sm"><span className="w-2.5 h-2.5 rounded-[var(--radius-pill)] bg-red-500/60 inline-block" /> <span className="text-accent-danger font-medium">{beyond20.length}</span> <span className="text-[var(--brand-text-muted)]">20+</span></span>
                <span className="flex items-center gap-1.5 t-caption-sm"><span className="w-2.5 h-2.5 rounded-[var(--radius-pill)] bg-[var(--surface-3)] inline-block" /> <span className="text-[var(--brand-text-muted)] font-medium">{notRankingCount}</span> <span className="text-[var(--brand-text-muted)]">Not ranking</span></span>
              </div>
              {Object.keys(intentCounts).length > 1 && (
                <div className="mt-3 pt-3 border-t border-[var(--brand-border)]">
                  <div className="t-caption-sm text-[var(--brand-text-muted)] uppercase tracking-wider mb-1.5">Search Intent Mix</div>
                  <div className="flex items-center gap-2 flex-wrap">
                    {Object.entries(intentCounts).sort((a, b) => b[1] - a[1]).map(([intent, count]) => (
                      <span key={intent} className={`t-caption-sm px-2 py-0.5 rounded-[var(--radius-pill)] border font-medium ${intentColor(intent)}`}>
                        {intent} ({count})
                      </span>
                    ))}
                  </div>
                </div>
              )}
            </SectionCard>
          )}

          {/* ── Quick Wins ── */}
          <div id="quick-wins-section">
            <QuickWins quickWins={strategy.quickWins || []} />
          </div>

          {/* ── Low-Hanging Fruit ── */}
          <LowHangingFruit pages={lowHangingFruit} positionColor={positionColor} />

          {/* ── Content Gaps ── */}
          <ContentGaps contentGaps={strategy.contentGaps || []} workspaceId={workspaceId} intentColor={intentColor} />

          {/* Keyword Gaps */}
          <KeywordGaps keywordGaps={strategy.keywordGaps || []} difficultyColor={difficultyColor} />

          {/* ── Reference & Analysis ── */}
          <div className="border-t border-[var(--brand-border)] my-6 flex items-center gap-3">
            <span className="t-caption text-[var(--brand-text-muted)] uppercase tracking-wide">Reference & Analysis</span>
            <div className="flex-1 border-t border-[var(--brand-border)]" />
          </div>

          {/* ── Topical Authority ── */}
          {strategy.topicClusters && strategy.topicClusters.length > 0 && (
            <TopicClusters clusters={strategy.topicClusters} />
          )}

          {/* ── Cannibalization Alert ── */}
          {strategy.cannibalization && strategy.cannibalization.length > 0 && (
            <CannibalizationAlert items={strategy.cannibalization} />
          )}

          {/* ── What Changed (Strategy Diff) ── */}
          <StrategyDiff workspaceId={workspaceId} />

          {/* Backlink Profile */}
          <BacklinkProfile workspaceId={workspaceId} />

          {/* Competitive Intelligence Hub */}
          <CompetitiveIntel
            workspaceId={workspaceId}
            competitors={competitors.split(/[,\n]+/).map(c => c.trim()).filter(Boolean)}
            seoDataAvailable={seoDataAvailable}
            cachedKeywordGaps={strategy?.keywordGaps}
          />

          {/* ── Site Keywords ── */}
          <SectionCard
            title="Site Target Keywords"
            titleIcon={<Icon as={Target} size="md" className="text-accent-brand" />}
          >
            <div className="flex flex-wrap gap-1.5">
              {strategy.siteKeywords.map((kw: string, i: number) => {
                const metrics = strategy.siteKeywordMetrics?.find((m: { keyword: string; volume: number; difficulty: number }) => m.keyword.toLowerCase() === kw.toLowerCase());
                const tracked = trackedKeywords.has(kw);
                return (
                  <span key={i} className="inline-flex items-center gap-1.5 px-2 py-0.5 bg-teal-500/10 border border-teal-500/20 rounded t-caption-sm text-accent-brand">
                    {kw}
                    {metrics && (metrics.volume > 0 || metrics.difficulty > 0) && (
                      <>
                        {metrics.volume > 0 && <span className="t-caption-sm text-[var(--brand-text-muted)] font-mono">{metrics.volume.toLocaleString()}/mo</span>}
                        {metrics.difficulty > 0 && <span className={`t-caption-sm font-mono ${difficultyColor(metrics.difficulty)}`}>KD {metrics.difficulty}%</span>}
                      </>
                    )}
                    <button
                      onClick={() => trackKeyword(kw)}
                      title={tracked ? 'Tracking' : 'Track in Rank Tracker'}
                      className={`ml-0.5 transition-colors ${tracked ? 'text-accent-success' : 'text-[var(--brand-text-muted)] hover:text-accent-brand'}`}
                    >
                      {tracked ? <Icon as={Check} size="sm" className="text-accent-success" /> : <Icon as={Plus} size="sm" />}
                    </button>
                  </span>
                );
              })}
            </div>
          </SectionCard>

          {/* ── Opportunities ── */}
          {strategy.opportunities.length > 0 && (
            <SectionCard
              title="Keyword Opportunities"
              titleIcon={<Icon as={Sparkles} size="md" className="text-accent-brand" />}
            >
              <p className="text-[var(--brand-text-muted)] t-caption-sm mb-2">
                These opportunities are AI-generated suggestions based on your site's content and competitive landscape. Validate with keyword research before acting.
              </p>
              <div className="space-y-1.5">
                {strategy.opportunities.map((opp: string, i: number) => (
                  <div key={i} className="flex items-start gap-2 t-caption-sm text-[var(--brand-text)]">
                    <span className="w-4 h-4 rounded-[var(--radius-pill)] bg-teal-500/10 border border-teal-500/20 flex items-center justify-center flex-shrink-0 mt-0.5 t-caption-sm text-accent-brand font-bold">{i + 1}</span>
                    {opp}
                  </div>
                ))}
              </div>
            </SectionCard>
          )}

          {/* How it works */}
          <div className="bg-[var(--surface-3)]/30 rounded-[var(--radius-lg)] border border-[var(--brand-border)] px-4 py-3">
            <div className="flex items-start gap-2">
              <Icon as={Sparkles} size="md" className="text-accent-brand mt-0.5 flex-shrink-0" />
              <div className="t-caption-sm text-[var(--brand-text-muted)]">
                <strong className="text-[var(--brand-text)]">How it works:</strong> This strategy is automatically used when you generate AI rewrites
                in the Edit SEO and CMS SEO tabs. The AI will incorporate your target keywords naturally into titles and descriptions.
                Use <strong className="text-accent-brand">Page Intelligence</strong> to analyze individual pages, edit keywords, and generate SEO copy.
                {displayedSeoDataMode && displayedSeoDataMode !== 'none' && (
                  <span className="block mt-1 text-accent-orange">
                    SEO provider data: Keywords enriched with real search volume and difficulty. Cached for 7 days.
                  </span>
                )}
                {!(strategy.pageMap ?? []).some((p: PageKeywordMap) => p.currentPosition) && (
                  <span className="block mt-1 text-accent-warning">
                    Tip: Connect Google Search Console to see ranking positions and get data-driven keyword suggestions.
                  </span>
                )}
              </div>
            </div>
          </div>
        </>
      )}
      </div>}
    </div>
  );
}
