import { useState, useEffect } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { Target, FileText } from 'lucide-react';
import { AIContextIndicator, TabBar, ErrorState, EmptyState, ProgressIndicator, NextStepsCard, LoadingState, PageHeader, Icon } from './ui';
import { formatDate } from '../utils/formatDates';
import { kdColor } from './page-intelligence/pageIntelligenceDisplay';
import { useKeywordStrategy } from '../hooks/admin';
import { useAdminRecommendationSet } from '../hooks/admin/useAdminRecommendations';
import { useRecommendationLifecycle } from '../hooks/admin/useRecommendationLifecycle';
import { useContentDecay } from '../hooks/admin/useContentDecay';
import { useFeatureFlag } from '../hooks/useFeatureFlag';
import { resolveTabSearchParam, clearTabSearchParam } from '../lib/tab-search-param';
import { RefreshOrderingPrompt } from './keyword-strategy/RefreshOrderingPrompt';
import { ContentGaps } from './strategy/ContentGaps';
import { QuickWins } from './strategy/QuickWins';
import { KeywordGaps } from './strategy/KeywordGaps';
import { LowHangingFruit } from './strategy/LowHangingFruit';
import { TopicClusters } from './strategy/TopicClusters';
import { CannibalizationAlert } from './ui/CannibalizationAlert';
import { StrategyDiff } from './strategy/StrategyDiff';
import { IntelligenceSignals } from './strategy/IntelligenceSignals';
import { LocalSeoVisibilityPanel } from './local-seo/LocalSeoVisibilityPanel';
import {
  useStrategyMetrics,
  useStrategySettings,
  useStrategyGeneration,
  useTrackKeyword,
  useKeywordFeedback,
  StrategyHeaderActions,
  StrategyFeedbackNudge,
  ClientKeywordFeedback,
  StrategySettings,
  StrategyStalenessNudges,
  StrategyEmptyState,
  OrientZone,
  ActQueue,
  StrategyCockpit,
  DecayingPagesCard,
  StrategyRankingsTab,
  StrategyCompetitiveTab,
  SiteTargetKeywords,
  KeywordOpportunities,
  StrategyHowItWorks,
} from './strategy';
import { adminPath } from '../routes';

// Strategy v2 interior tabs (command-center layout). Overview = Orient + Act + reference;
// Content = the content "money page"; Rankings = position distribution + movements;
// Competitive = share of voice + keyword gaps + backlinks (the "research mode" surface).
// The literal ids appear here so the ?tab= deep-link contract test recognizes this receiver.
type StrategyInteriorTab = 'overview' | 'content' | 'rankings' | 'competitive';
const STRATEGY_INTERIOR_TABS: { id: StrategyInteriorTab; label: string }[] = [
  { id: 'overview', label: 'Overview' },
  { id: 'content', label: 'Content' },
  { id: 'rankings', label: 'Rankings' },
  { id: 'competitive', label: 'Competitive' },
];

interface Props {
  workspaceId: string;
  siteId?: string;
}

export function KeywordStrategyPanel({ workspaceId }: Props) {
  const navigate = useNavigate();
  // Strategy v2 interior tab (?tab= deep-link, two-halves contract — mirrors ContentPipeline).
  const [searchParams, setSearchParams] = useSearchParams();
  const [interiorTab, setInteriorTab] = useState<StrategyInteriorTab>(() =>
    resolveTabSearchParam<StrategyInteriorTab>(searchParams.get('tab'), {
      validValues: STRATEGY_INTERIOR_TABS.map((t) => t.id),
      fallback: 'overview',
    }),
  );
  useEffect(() => {
    const param = searchParams.get('tab');
    if (param && STRATEGY_INTERIOR_TABS.some((t) => t.id === param) && param !== interiorTab) {
      setInteriorTab(param as StrategyInteriorTab);
    }
  }, [searchParams]); // eslint-disable-line react-hooks/exhaustive-deps -- sync interior tab to external ?tab= changes only

  // React Query hook replaces manual data fetching
  const { data: keywordData, isLoading: loading, isAuxLoading, isError: strategyFetchError, refetch: refetchStrategy } = useKeywordStrategy(workspaceId);
  const strategy = keywordData?.strategy || null;
  // A "real" strategy has been generated by the AI pipeline (non-null generatedAt).
  // The server may synthesize a shell { pageMap, generatedAt: null, siteKeywords: [], opportunities: [] }
  // when page_keywords rows exist but no strategy blob — that case must render as "no strategy yet"
  // in this component, while still exposing pageMap via Page Intelligence separately.
  const isRealStrategy = strategy?.generatedAt != null;
  const displayedSeoDataMode = strategy?.seoDataMode;

  // Local ↔ Strategy sync status — present when workspace posture is local or hybrid.
  const localSync = keywordData?.strategy?.strategyUx?.localSync;

  // ── Logic hooks (extracted from this orchestrator in Phase 0) ──
  const settings = useStrategySettings(keywordData, strategy, workspaceId);
  const generation = useStrategyGeneration({
    workspaceId,
    localSync,
    buildStrategyGenerationParams: settings.buildStrategyGenerationParams,
  });
  const tracking = useTrackKeyword(workspaceId);
  const feedback = useKeywordFeedback(workspaceId);
  const metrics = useStrategyMetrics(strategy, feedback.rows, isRealStrategy);
  // Flag gate: flag-ON renders v3 StrategyCockpit; flag-OFF preserves the v2 Act queue exactly.
  // Called unconditionally here (before all early returns) — Rules of Hooks.
  const commandCenterEnabled = useFeatureFlag('strategy-command-center');
  // The v2 Act queue reads the unified recommendation set (separately generated from the strategy
  // blob). Read it here too — sharing the React Query cache with ActQueue — to decide whether the
  // queue actually has content yet; if not, the legacy action sections stay as a fallback.
  const { data: recommendationSet } = useAdminRecommendationSet(workspaceId);
  const hasActiveRecommendations = (recommendationSet?.recommendations ?? []).some(
    (r) => r.status !== 'dismissed' && r.status !== 'completed',
  );
  // Strategy v3 — lifecycle actions wired to admin routes; cockpit consumes the full rec set
  // (it has its own lifecycle/category facets + Fix-now pin, so it filters internally).
  const lifecycleActions = useRecommendationLifecycle(workspaceId);
  const cockpitRecs = recommendationSet?.recommendations ?? [];
  // Content-tab emptiness (v2) — used to render an action-oriented EmptyState rather than a blank
  // tab when no content opportunities exist.
  const { data: contentDecayData } = useContentDecay(workspaceId);

  // Competitor domains as a clean array — consumed by the Competitive tab (StrategyCompetitiveTab)
  // so the CSV/newline parse lives in exactly one place.
  const competitorList = settings.competitors.split(/[,\n]+/).map((c) => c.trim()).filter(Boolean);

  // intentColor is consumed by ContentGaps — kept in the orchestrator and passed down.
  const intentColor = (intent?: string) => {
    switch (intent) {
      case 'commercial': return 'text-accent-info bg-blue-500/10 border-blue-500/20';
      case 'informational': return 'text-accent-success bg-emerald-500/10 border-emerald-500/20';
      case 'transactional': return 'text-accent-warning bg-amber-500/10 border-amber-500/20';
      case 'navigational': return 'text-accent-cyan bg-cyan-500/10 border-cyan-500/20';
      default: return 'text-[var(--brand-text)] bg-zinc-500/10 border-zinc-500/20'; // raw-zinc-ok
    }
  };

  if (loading) {
    return <LoadingState message="Loading keyword strategy..." />;
  }

  if (strategyFetchError) {
    return (
      <ErrorState
        type="general"
        title="Failed to load keyword strategy"
        message="There was a problem loading your keyword strategy. Please try again."
        action={{ label: 'Retry', onClick: () => void refetchStrategy() }}
      />
    );
  }

  if (!workspaceId) {
    return (
      <div className="text-center py-16 text-[var(--brand-text-muted)] t-body">
        No workspace selected. Link a workspace to generate a keyword strategy.
      </div>
    );
  }

  // Header subtitle: artifact freshness once a real strategy exists.
  const headerSubtitle = !isRealStrategy
    ? 'AI-powered keyword mapping for your entire site'
    : `Generated ${formatDate(strategy?.generatedAt)} · ${strategy?.pageMap?.length ?? 0} pages mapped`;

  // ── Shared elements (defined once; the two layouts arrange the same elements differently) ──
  const headerActions = (
    <StrategyHeaderActions
      isRealStrategy={isRealStrategy}
      generating={generation.generating}
      localSyncApplies={!!localSync?.applies}
      localNeedsRefresh={!!localSync?.localNeedsRefresh}
      refreshPending={generation.refresh.isPending}
      onIncremental={() => generation.generateStrategy('incremental')}
      onFullRefresh={() => generation.refresh.mutate({
        thenRegenerateStrategy: true,
        strategyGeneration: settings.buildStrategyGenerationParams(),
      })}
      onGenerate={() => generation.generateStrategy('full')}
    />
  );

  const headerEl = (
    <PageHeader
      title="Keyword Strategy"
      subtitle={headerSubtitle}
      icon={<Icon as={Target} size="lg" className="text-accent-brand" />}
      actions={headerActions}
    />
  );

  const refreshPromptEl = localSync?.applies && localSync.localNeedsRefresh ? (
    <RefreshOrderingPrompt
      open={generation.refreshOrderingPromptOpen}
      reason={localSync.localNeedsRefreshReason ?? 'stale'}
      lastLocalRefreshAt={localSync.lastLocalRefreshAt}
      onFullRefresh={() => {
        generation.refresh.mutate({
          thenRegenerateStrategy: true,
          strategyGeneration: settings.buildStrategyGenerationParams(),
        });
        generation.setRefreshOrderingPromptOpen(false);
      }}
      onGenerateAnyway={() => {
        generation.setRefreshOrderingPromptOpen(false);
        void generation.runStartJob('full');
      }}
      onCancel={() => generation.setRefreshOrderingPromptOpen(false)}
    />
  ) : null;

  const aiContextEl = !isRealStrategy && !generation.generating
    ? <AIContextIndicator workspaceId={workspaceId} feature="strategy" />
    : null;

  const localSeoEl = (
    <LocalSeoVisibilityPanel
      workspaceId={workspaceId}
      mode="strategy"
      onOpenKeywords={() => navigate(adminPath(workspaceId, 'seo-keywords'))}
    />
  );

  const feedbackNudgeEl = metrics.feedbackNewerThanStrategy ? (
    <StrategyFeedbackNudge
      requestedCount={metrics.requestedFeedback.length}
      declinedCount={metrics.declinedFeedback.length}
    />
  ) : null;

  const settingsEl = (
    <StrategySettings
      workspaceId={workspaceId}
      isAuxLoading={isAuxLoading}
      settingsOpen={settings.settingsOpen}
      setSettingsOpen={settings.setSettingsOpen}
      seoDataAvailable={settings.seoDataAvailable}
      seoDataMode={settings.seoDataMode}
      setSeoDataMode={settings.setSeoDataMode}
      maxPages={settings.maxPages}
      setMaxPages={settings.setMaxPages}
      competitors={settings.competitors}
      setCompetitors={settings.setCompetitors}
      businessContext={settings.businessContext}
      setBusinessContext={settings.setBusinessContext}
      contextOpen={settings.contextOpen}
      setContextOpen={settings.setContextOpen}
      discoveringCompetitors={settings.discoveringCompetitors}
      discoverError={settings.discoverError}
      onDiscoverCompetitors={settings.discoverCompetitors}
    />
  );

  const intelligenceSignalsEl = <IntelligenceSignals workspaceId={workspaceId} />;

  const progressEl = (
    <ProgressIndicator
      status={generation.generating ? 'running' : 'idle'}
      step={generation.activeStrategyJob?.message || (generation.startingStrategyJob ? 'Starting keyword strategy job...' : undefined)}
      percent={generation.activeStrategyJob?.total ? Math.round(((generation.activeStrategyJob.progress ?? 0) / generation.activeStrategyJob.total) * 100) : undefined}
    />
  );

  const errorEl = generation.error ? (
    <ErrorState
      type="general"
      title="Strategy Generation Failed"
      message={generation.error}
      action={{ label: 'Try Again', onClick: () => generation.generateStrategy('full') }}
    />
  ) : null;

  const nextStepsEl = generation.showNextSteps && isRealStrategy && !generation.generating ? (
    <NextStepsCard
      title="Strategy ready"
      variant="success"
      onDismiss={() => generation.setShowNextSteps(false)}
      staggerIndex={0}
      steps={[
        {
          label: 'Review Quick Wins',
          onClick: () => { generation.setShowNextSteps(false); setTimeout(() => document.getElementById('quick-wins-section')?.scrollIntoView({ behavior: 'smooth' }), 150); },
          estimatedTime: '2 min',
        },
      ]}
    />
  ) : null;

  const emptyStateEl = !isRealStrategy && !generation.generating ? <StrategyEmptyState /> : null;

  const clientFeedbackCombinedEl = (
    <ClientKeywordFeedback
      rows={feedback.rows}
      requested={metrics.requestedFeedback}
      declined={metrics.declinedFeedback}
      approved={metrics.approvedFeedback}
      addPending={feedback.addPending}
      addError={feedback.addError}
      onAdd={feedback.addRequestedKeyword}
      onDismissError={() => feedback.setAddError(null)}
    />
  );

  // Real-strategy leaf elements — identical in both layouts; only the grouping/order differs.
  const realLeaves = isRealStrategy && strategy ? {
    stalenessNudges: (
      <StrategyStalenessNudges
        hasVolumeValidation={metrics.hasVolumeValidation}
        localSyncApplies={!!localSync?.applies}
        strategyStaleVsLocal={!!localSync?.strategyStaleVsLocal}
        lastLocalRefreshAt={localSync?.lastLocalRefreshAt}
        lastStrategyGeneratedAt={localSync?.lastStrategyGeneratedAt}
        dismissedRefreshAt={generation.dismissedRefreshAt}
        onDismiss={() => generation.setDismissedRefreshAt(localSync?.lastLocalRefreshAt ?? null)}
        onGenerate={() => generation.generateStrategy('full')}
      />
    ),
    quickWins: (
      <div id="quick-wins-section">
        <QuickWins quickWins={strategy.quickWins ?? []} />
      </div>
    ),
    lhf: <LowHangingFruit pages={metrics.lowHangingFruit} />,
    contentGaps: <ContentGaps contentGaps={strategy.contentGaps || []} workspaceId={workspaceId} intentColor={intentColor} />,
    keywordGaps: (
      <KeywordGaps
        keywordGaps={strategy.keywordGaps || []}
        difficultyColor={kdColor}
        workspaceId={workspaceId}
        navigate={navigate}
      />
    ),
    topicClusters: strategy.topicClusters && strategy.topicClusters.length > 0
      ? <TopicClusters clusters={strategy.topicClusters} />
      : null,
    decayingPages: <DecayingPagesCard workspaceId={workspaceId} />,
    cannibalization: strategy.cannibalization && strategy.cannibalization.length > 0
      ? <CannibalizationAlert entries={strategy.cannibalization} />
      : null,
    strategyDiff: <StrategyDiff workspaceId={workspaceId} />,
    siteKeywords: (
      <SiteTargetKeywords
        workspaceId={workspaceId}
        siteKeywords={strategy.siteKeywords}
        siteKeywordMetrics={strategy.siteKeywordMetrics}
        trackedKeywords={tracking.trackedKeywords}
        trackingPending={tracking.trackingPending}
        trackingErrors={tracking.trackingErrors}
        onTrack={tracking.trackKeyword}
      />
    ),
    opportunities: <KeywordOpportunities opportunities={strategy.opportunities} />,
    howItWorks: <StrategyHowItWorks displayedSeoDataMode={displayedSeoDataMode} hasAnyRanking={metrics.hasAnyRanking} />,
  } : null;

  // Strategy command-center Orient zone (the cutover baseline — always rendered for a real strategy).
  const orientEl = isRealStrategy
    ? <OrientZone orient={strategy?.strategyUx?.orient} />
    : null;
  // Act zone — the unified impact-ranked recommendation queue. It replaces the quick-wins / LHF /
  // keyword-gaps sections ONLY once the recommendation set actually has content. Until then (fresh
  // strategy before regen runs, a pre-engine workspace, or a fetch error) those sections stay as a
  // fallback so no actionable content is hidden behind an empty queue.
  const useActQueue = isRealStrategy && hasActiveRecommendations;
  const actQueueEl = useActQueue ? <ActQueue workspaceId={workspaceId} /> : null;
  // v3 cockpit element — only constructed when the flag is on, reuses the already-fetched rec set.
  const cockpitEl = (commandCenterEnabled && isRealStrategy)
    ? <StrategyCockpit workspaceId={workspaceId} recs={cockpitRecs} actions={lifecycleActions} />
    : null;

  const handleInteriorTabChange = (id: string) => {
    setInteriorTab(id as StrategyInteriorTab);
    const next = clearTabSearchParam(searchParams);
    if (next) setSearchParams(next, { replace: true });
  };

  // Content-tab presence — drives the EmptyState when nothing is actionable (a common early state).
  const hasContentGaps = (strategy?.contentGaps?.length ?? 0) > 0;
  const hasTopicClusters = (strategy?.topicClusters?.length ?? 0) > 0;
  const hasDecayingPages = (contentDecayData?.decayingPages?.length ?? 0) > 0;
  const hasContentTabContent = hasContentGaps || hasTopicClusters || hasDecayingPages;

  // ── Strategy command-center layout (the baseline): page chrome + interior tabs (Overview / Content) ──
  const strategyLayout = (
    <div className="space-y-8">
      {headerEl}
      {refreshPromptEl}
      {aiContextEl}
      {localSeoEl}
      {progressEl}
      {errorEl}
      {nextStepsEl}
      {/* clientFeedbackCombinedEl + settingsEl are rendered unconditionally so they are visible
          even before the first strategy is generated (no-strategy state). Interim: this also shows
          them on all interior tabs until StrategyCockpit (Phase 2) re-homes them. */}
      {clientFeedbackCombinedEl}
      {settingsEl}
      {emptyStateEl}
      {realLeaves && (
        <>
          <TabBar tabs={STRATEGY_INTERIOR_TABS} active={interiorTab} onChange={handleInteriorTabChange} />
          {interiorTab === 'overview' && (
            <div className="space-y-8">
              {feedbackNudgeEl}
              {realLeaves.stalenessNudges}
              {orientEl}
              {(commandCenterEnabled ? cockpitEl : actQueueEl) ?? (
                <>
                  {realLeaves.quickWins}
                  {realLeaves.lhf}
                  {realLeaves.keywordGaps}
                </>
              )}
              {/* ── Reference & Analysis ── */}
              <div className="border-t border-[var(--brand-border)] my-6 flex items-center gap-3">
                <span className="t-caption text-[var(--brand-text-muted)] uppercase tracking-wide">Reference & Analysis</span>
                <div className="flex-1 border-t border-[var(--brand-border)]" />
              </div>
              {realLeaves.cannibalization}
              {realLeaves.strategyDiff}
              {realLeaves.siteKeywords}
              {realLeaves.opportunities}
              {intelligenceSignalsEl}
              {realLeaves.howItWorks}
            </div>
          )}
          {interiorTab === 'content' && (
            <div className="space-y-8">
              {hasContentTabContent ? (
                <>
                  <p className="t-caption text-[var(--brand-text-muted)]">Reference view — actionable content items also surface in the Act queue on Overview.</p>
                  {realLeaves.contentGaps}
                  {realLeaves.topicClusters}
                  {realLeaves.decayingPages}
                </>
              ) : (
                <EmptyState
                  icon={FileText}
                  title="No content opportunities yet"
                  description="Generate or refresh your strategy to surface content gaps, topic-cluster gaps, and decaying pages to act on."
                />
              )}
            </div>
          )}
          {interiorTab === 'rankings' && (
            <StrategyRankingsTab metrics={metrics} workspaceId={workspaceId} navigate={navigate} />
          )}
          {interiorTab === 'competitive' && (
            <StrategyCompetitiveTab
              workspaceId={workspaceId}
              competitors={competitorList}
              seoDataAvailable={settings.seoDataAvailable}
              keywordGaps={strategy?.keywordGaps || []}
              navigate={navigate}
            />
          )}
        </>
      )}
    </div>
  );

  // Command-center layout is the baseline (v2 cutover) — interior ?tab= tabs, no Analysis/Guide TabBar.
  return strategyLayout;
}
