/**
 * CMS page filtering utilities for SeoEditor bulk operations.
 *
 * CMS pages discovered via sitemap get synthetic IDs (format: 'cms-*').
 * These are not real Webflow page IDs — the Webflow API rejects them with 404.
 * All bulk operations that write to Webflow must use these utilities to exclude
 * CMS pages from the write batch.
 *
 * Extracted to a shared module so that:
 *   1. SeoEditor.tsx uses consistent, named predicates instead of inline checks
 *   2. tests/unit/seoEditorCmsFilter.test.ts imports the real implementations —
 *      any regression in the filtering logic will be caught by the tests
 */

import type { PageMeta } from './useSeoEditor.js';

/**
 * Returns true if the pageId is a synthetic CMS discovery ID.
 * Synthetic IDs are generated by the all-pages endpoint for CMS pages
 * found via sitemap and are NOT valid Webflow page or collection-item IDs.
 */
export const isSyntheticCmsId = (pageId: string): boolean =>
  pageId.startsWith('cms-');

/**
 * Filters a PageMeta array to only static pages.
 * Use this before any loop that writes to the Webflow API.
 */
export const filterWritablePages = (pages: PageMeta[]): PageMeta[] =>
  pages.filter(p => p.source !== 'cms');

/**
 * Filters an array of objects with a `pageId` field to only those whose
 * corresponding page is a static (writable) page.
 * Use for bulk-preview items and pattern-preview items before sending to Webflow.
 */
export const filterWritableItems = <T extends { pageId: string }>(
  items: T[],
  pages: PageMeta[],
): T[] =>
  items.filter(item => pages.find(p => p.id === item.pageId)?.source !== 'cms');

/**
 * Filters an array of page ID strings to only those referencing static pages.
 * Use for approvalSelected before building previews or payloads.
 */
export const filterWritableIds = (
  selectedIds: string[],
  pages: PageMeta[],
): string[] =>
  selectedIds.filter(id => pages.find(p => p.id === id)?.source !== 'cms');

/**
 * Counts static pages missing the given SEO field.
 * Used to populate the 'AI Fix Titles (N)' / 'AI Fix Descriptions (N)' badges.
 * CMS pages are excluded — they can never be written via the Webflow API.
 */
export const countMissingField = (
  pages: PageMeta[],
  field: 'title' | 'description',
): number =>
  pages.filter(p =>
    p.source !== 'cms' &&
    (field === 'title' ? !p.seo?.title : !p.seo?.description),
  ).length;

/**
 * Filters a PageMeta array to static pages that are missing the given SEO field.
 * Used as the input for handleBulkFix.
 */
export const filterPagesNeedingFix = (
  pages: PageMeta[],
  field: 'title' | 'description',
): PageMeta[] =>
  pages.filter(p => {
    if (p.source === 'cms') return false;
    return field === 'title' ? !p.seo?.title : !p.seo?.description;
  });
